### ISSUE TITLE
Order for 'peng' is wrong

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#13]
It should be Kopi Peng Gah Dai instead of Kopi Gah Dai Peng. Not sure for other expressions tho'.

@chuyeow @soulofpeace any ideas?

**Comment by cheeaun** [comment]
Fixed in fece074df7df4c5f158a1794e119ae25eb6da985

**Comment by rctay** [comment]
Based on what I have "tia gong" at coffeeshops, 'peng' could come after `sweetnessText`, eg. kopi c kosong peng (`sweetnessText` = "kosong"). Dunno.
