### ISSUE TITLE
KopiJS 9th meetup - 24th Jan 2015

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#20]
As usual, it's a meetup for kopi lovers where we'll hang out and talk about Kopi, JS and anything.

(New) website: http://kopijs.org/
Lanyrd: http://lanyrd.com/2015/kopijs/
Date: **Saturday, 24 Jan 2015, 11AM**
Location: [**Chin Mee Chin Confectionery**](https://foursquare.com/v/chin-mee-chin-confectionery/4b2d8577f964a5204fd824e3), [204 East Coast Road, Singapore 428903](https://www.google.com.sg/maps/place/Chin+Mee+Chin+Confectionery/@1.307236,103.907052,15z/data=!4m2!3m1!1s0x0:0x6462d2e6d567a107)

*****
SUPER IMPORTANT
===

- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.
- **TRACK** the event via [Lanyrd](http://lanyrd.com/2015/kopijs/).

*****

##### Agenda

1. Gather at Chin Mee Chin. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) all the tables.
2. Drink Kopi/Teh/Milo/whatever. Eat brunch also can if hungry.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- Got free stickers!
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun) or [@laktek](https://twitter.com/laktek).

**RSVP** by :+1:-ing this issue!

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @ctrlaltreboot @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @kaihendry @zz85 @miccheng and anyone

**Comment by cheeaun** [comment]
Free stickers!

![](https://pbs.twimg.com/media/B5Bj3rUCYAA-VB1.jpg:large)

**Comment by stuti90** [comment]
:+1: :smile:

**Comment by miccheng** [comment]
Inviting @liuziyi

**Comment by creativepsyco** [comment]
:+1: inviting @chenzihui @meiwin @gigablah @angelorohit

**Comment by yohanesyuen** [comment]
I should be joining. :D Cool project you guys have here! ^^

**Comment by cheeaun** [comment]
@yohanesyuen :+1: thanks

**Comment by notthetup** [comment]
Can't attend. Travelling :(

**Comment by cheeaun** [comment]
@notthetup :sob:

**Comment by sayanee** [comment]
i'm coming :dancer:

**Comment by sayanee** [comment]
:+1:

**Comment by miccheng** [comment]
See you guys!

**Comment by Valentine** [comment]
Inviting @hpdang. See you guys later!

**Comment by cheeaun** [comment]
Everyone, thanks again for coming and sharing all the stories/webrtc/yongfook/instagrams/food!

Not many tweets this time: https://twitter.com/search?q=kopijs%20since%3A2015-01-23%20until%3A2015-01-25&src=typd

Some photos:
[![](https://pbs.twimg.com/media/B8FsVRSCIAEUrBg.jpg:large)](https://twitter.com/laktek/status/558846955103588352)
[![](http://photos-b.ak.instagram.com/hphotos-ak-xpa1/t51.2885-15/924616_1584116285137433_219382866_n.jpg)](http://instagram.com/p/yOQcOclkA7/)

And more photos on Facebook:
https://www.facebook.com/photo.php?fbid=10153079312142229&set=a.475431307228.261529.503517228&type=1
https://www.facebook.com/miccheng/posts/10153079340857229

For those wondering, the Chope book comes from here: http://www.thelittledromstore.com/chope/book/

So.. keeping track of attendees:

- Myself :coffee: 
- @laktek 
- @miccheng 
- @serrynaimo
- @cbas
- @sayanee 
- @stuti90 
- @creativepsyco
- @Valentine 
- @gigablah
- @ardydedase
- @hpdang
- probbaly @liuziyi ?
- anyone else?

Closing the issue now...

**Comment by miccheng** [comment]
Let me make my photos public. :)

**Comment by cheeaun** [comment]
@miccheng :+1:

**Comment by creativepsyco** [comment]
@cheeaun @laktek thanks for organising :+1:

**Comment by Valentine** [comment]
Here's another group photo!

![p1244191 2048](https://cloud.githubusercontent.com/assets/676061/5970659/1f59564a-a871-11e4-9b48-db510d360f7a.jpg)

**Comment by sayanee** [comment]
:tada: :camera:

**Comment by cheeaun** [comment]
:+1:
