### ISSUE TITLE
KopiJS 10th meetup - 14th Feb 2015 - Valentine's Day special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#21]
It's @Valentine 's day. So it's a time for yet another meetup.

This is a meetup for kopi lovers where we'll hang out and talk about :coffee:, JS and :heart: :heart: :heart:.

Website: http://kopijs.org/
Lanyrd: http://lanyrd.com/2015/kopi-js/
Date: **Saturday, 14 Feb 2015, 11:30AM - Valentine's day**
Location: [**Creamier**](http://creamier.com.sg/) - [Facebook](https://www.facebook.com/creamier.singapore), [Twitter](https://twitter.com/Creamier_sg), [Foursquare](https://foursquare.com/v/creamier-ice-cream-and-coffee/4e9fb0b46c258f17cb31f906)
Location address: [Blk128, Toa Payoh Lorong 1, #01-835](https://www.google.com.sg/maps/place/Creamier+Handcrafted+Ice+Cream+and+Coffee/@1.337753,103.844211,17z/data=!3m1!4b1!4m2!3m1!1s0x31da17428516e5b7:0x4a1ebfe28a9d58a4) (Nearest MRT station: **Braddell** on red line)
[![](http://maps.googleapis.com/maps/api/staticmap?scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:red%7Clabel:%7C1.337753,103.844211)](https://www.google.com.sg/maps/place/Creamier+Handcrafted+Ice+Cream+and+Coffee/@1.337753,103.844211,17z/data=!3m1!4b1!4m2!3m1!1s0x31da17428516e5b7:0x4a1ebfe28a9d58a4)

*****
SUPER IMPORTANT
===

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Creamier. Wait for the shop to open. Once open, [chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) all the tables.
2. Drink Kopi/Teh/Milo/whatever. Eat brunch also can if hungry.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue!

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @ctrlaltreboot @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @kaihendry @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase and anyone

**Comment by zz85** [comment]
chong pang!

**Comment by zz85** [comment]
@laktek says http://creamier.com.sg/

**Comment by sayanee** [comment]
:+1:

**Comment by miccheng** [comment]
Yeah, Creamier has nice ice cream and has sitting space inside. Hawker center nearby too has good food. Nearest MRT is Braddell MRT. Ha ha... My old home stead.

**Comment by zz85** [comment]
ok! next time then have kopi at my sembawang kampung k?.. actually i might be away on the date, but otherwise :+1:

**Comment by Valentine** [comment]
:+1:

**Comment by ardydedase** [comment]
:thumbsup:

**Comment by Valentine** [comment]
Inviting @stephanfeb!

**Comment by cheeaun** [comment]
Inviting more peeps @ahkeno @soareschen @renettarenula @dqminh @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston

**Comment by miccheng** [comment]
Inviting @yongfook

**Comment by renettarenula** [comment]
:+1:

**Comment by cheeaun** [comment]
Alright guys, settling on Creamier. It opens at 12:00 but we'll gather at 11:30 and wait for the shop to open :smiling_imp: . Remember to add this event to your calendar and see you all there! :coffee:

**Comment by notthetup** [comment]
:+1:

**Comment by winston** [comment]
Sorry would really love to join. But I have something on at 12+. If this is happening at 10+ would be great. Till next time! :)

**Comment by cheeaun** [comment]
@winston :sob:

**Comment by cheeaun** [comment]
Inviting more peeps: @kahwee @chikathreesix

**Comment by chikathreesix** [comment]
Going :+1:

**Comment by stuti90** [comment]
won't be able to make it this time :sob:  but i'll definitely join next time!

**Comment by cheeaun** [comment]
@stuti90 :sob: :broken_heart:

**Comment by sayanee** [comment]
+1 for @shiawuen :+1:

**Comment by shiawuen** [comment]
:+1:

**Comment by stephanfeb** [comment]
+1

Stephan

On 12 Feb 2015, at 23:20, Tan Shiaw Uen <notifications@github.com> wrote:

[image: :+1:]

—
Reply to this email directly or view it on GitHub
<https://github.com/KopiJS/kopi.js/issues/21#issuecomment-74087946>.

**Comment by creativepsyco** [comment]
:+1: I shall be there.

**Comment by gigablah** [comment]
:+1:

**Comment by yohanesyuen** [comment]
:+1:

**Comment by kahwee** [comment]
Sorry, I can't make it. It's my friend's baby shower. Have fun. Will join the next one. :)

**Comment by zz85** [comment]
i got distracted with some code this morning - will reach in about an hour's time.

**Comment by serrynaimo** [comment]
Will no be able to come before 1pm :(

**Comment by soareschen** [comment]
Gonna be one hour late. Just woke up..

**Comment by cheeaun** [comment]
Everyone, thanks for coming and choping the tables!

Some photos
- by @zz85 : https://twitter.com/BlurSpline/status/566526060594864128
- by @miccheng :
    - https://www.facebook.com/miccheng/posts/10153125531822229
    - https://www.facebook.com/miccheng/posts/10153125602907229
    - https://www.facebook.com/miccheng/posts/10153125530232229

![](https://pbs.twimg.com/media/B9y0UzYCEAAr0Un.jpg)

And the attendees:

- Myself :icecream: 
- @laktek 
- @zz85 
- @sayanee 
- @notthetup 
- @renettarenula 
- @soareschen 
- @chikathreesix 
- @ardydedase 
- @stephanfeb 
- @shiawuen + 1
- @serrynaimo 
- @creativepsyco 
- @gigablah 
- @phungleson
- @liuziyi
- @kaihendry + 1
- @gibtang
- anyone else?

Few notes:

- Place is very nice and hipster-ish but too popular so a lot of people actually wait for it to open and prepare choping tables.
- Playground outside is a nice touch. Nearby food court is also nice.
- @Valentine [ffk](http://www.urbandictionary.com/define.php?term=ffk&defid=4465996) us, despite all the hype and marketing efforts :broken_heart: 
- Probably need to invest in a cheap selfie rod? :camera: 

Closing the issue now...

**Comment by Valentine** [comment]
Sorry!!! Was incapacitated due to excessive ethanol and quinine consumption last night. :disappointed:

**Comment by yohanesyuen** [comment]
Sorry guys. Overslept jialat. ><

**Comment by cheeaun** [comment]
@Valentine @yohanesyuen no problem. Next meetup then :smile:

**Comment by stephanfeb** [comment]
Short video clip of the event is up !

https://www.youtube.com/watch?v=omLQKdKt8Uk&feature=youtu.be

**Comment by cheeaun** [comment]
@stephanfeb wow thanks! That looks awesome! :heart:
