### ISSUE TITLE
KopiJS 11th meetup - 28th Feb 2015

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#24]
As usual, it's a meetup for kopi lovers where we'll hang out and talk about Kopi, JS and anything.

Are you **NEW** to this meetup? Please **READ** this article:

### :coffee: [The Kopi.JS meetup story](https://medium.com/@cheeaun/the-kopi-js-meetup-story-5ee2cd574678)

Website: http://kopijs.org/
Lanyrd: http://lanyrd.com/2015/kopijs-february/
Date: **Saturday, 28 Feb 2015, 11:00AM**
Location: [**Ya Kun Kaya Toast**](https://foursquare.com/v/ya-kun-kaya-toast-%E4%BA%9E%E5%9D%A4/4b231bc2f964a520635324e3), [18 China St #01-01 Singapore 049560](https://www.google.com.sg/maps/place/Ya+Kun+Kaya+Toast,+18+China+St,+Singapore+049560/@1.283737,103.84788,17z/data=!4m2!3m1!1s0x31da190c639bfa6f:0xc2d759952fbf4687)
Nearby MRT stations: Telok Ayer (blue line), Raffles Place (red, green), Chinatown (blue, purple)
[![](http://maps.googleapis.com/maps/api/staticmap?center=18+China+St,+Singapore&zoom=16&scale=2&size=640x320&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1EhKQfZ.png%7Cshadow:true%7C18+China+St,+Singapore)](https://www.google.com.sg/maps/place/Ya+Kun+Kaya+Toast,+18+China+St,+Singapore+049560/@1.283737,103.84788,17z/data=!4m2!3m1!1s0x31da190c639bfa6f:0xc2d759952fbf4687)
[Get directions :earth_asia:](https://www.google.com/maps/dir/Current%20Location/Ya%20Kun%20Kaya%20Toast%2C%2018%20China%20St%20%2301-01%20Singapore%20049560)

*****
SUPER IMPORTANT
===

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Ya Kun Kaya Toast. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) all the tables.
2. Drink Kopi/Teh/Milo/whatever. Eat brunch also can if hungry.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue!

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @ctrlaltreboot @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @laktek @ahkeno @soareschen @renettarenula @dqminh @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @yongfook @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen and anyone!

**Comment by gigablah** [comment]
:+1:

**Comment by notthetup** [comment]
No can do. Going for this.. http://www.sauvc.org/

**Comment by cheeaun** [comment]
@notthetup :sob:

**Comment by winston** [comment]
Can't too.. Helping with http://iamtalented.sg/

**Comment by cheeaun** [comment]
@winston :sob:

**Comment by miccheng** [comment]
Sama. Helping with that thingy.

**Comment by cheeaun** [comment]
@winston @miccheng date has changed. And @sindresorhus :+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by llun** [comment]
👆

**Comment by stuti90** [comment]
cant :sob: not in town!

**Comment by notthetup** [comment]
Nooo.. Clashing with our live podcast recording! http://live.webuild.sg/ Maybe someone can get the Ya Kun to point their radio to the podcast instead. :stuck_out_tongue: :microphone: :radio:

**Comment by winston** [comment]
Yea! :+1:

**Comment by yohanesyuen** [comment]
:+1:

**Comment by Valentine** [comment]
Inviting @mariobehling.

**Comment by mariobehling** [comment]
@Valentine Awesome. Will join!

**Comment by yohanesyuen** [comment]
I've reached

**Comment by miccheng** [comment]
@cheeaun Sorry, can't make it today. Have some errands to run today. I'll msg if things changes.

**Comment by ardydedase** [comment]
@cheeaun sorry can't join today. see you on the next one!

**Comment by serrynaimo** [comment]
WebRTC hackathon still going :) drop by if you like! Free coffee and I've questions for @sindresorhus

**Comment by kahwee** [comment]
Lovely to see everyone today. @cheeaun @yohanesyuen @sindresorhus and others! I don't know your usernames. :laughing:

**Comment by gigablah** [comment]
<- Chris :)

**Comment by cheeaun** [comment]
Everyone, thanks for joining!

Photos are mostly taken by @mariobehling so will have to wait till it's posted on the Internetz.

And the attendees:

- Myself :coffee: 
- @gigablah 
- @winston 
- @sindresorhus 
- @mariobehling 
- @kahwee 
- @llun 
- @cbas
- @alyssaq
- @rodneyrehm
- @yohanesyuen 
- @aladine
- @miccheng (join during lunch)
- a guy named "Laurence" during after-lunch
- anyone else?

Few notes:

- Place is nice and not crowded at all, though weather is hot.
- KopiJS t-shirt proved to be useful for easy recognition (for the meetup and as a developer) :smile: 
- Planning is a little rushed this time but still okay, unfortunately clashes with @webuildsg 's [We Build SG Live](http://live.webuild.sg/) and @serrynaimo 's [WebRTC hackathon](http://www.meetup.com/Singapore-WebRTC-Meetup/events/220474387/).

Closing the issue now...
