### ISSUE TITLE
KopiJS 12th meetup - 12th March 2015 - @laktek -special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#26]
As usual, it's a meetup for kopi lovers where we'll hang out and talk about Kopi, JS and anything.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Thursday, 12 Mar 2015, 11:30AM**
Location: [Amoy Street Food Centre](https://foursquare.com/v/amoy-street-food-centre/4b305537f964a520fef824e3), [7 Maxwell Rd (Telok Ayer St / Amoy St), 069111 Singapore](https://www.google.com.sg/maps/place/Amoy+Street+Food+Centre/@1.2801464,103.8478132,17z/)

*****
SUPER IMPORTANT
===

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Amoy Street Food Centre. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat brunch also can if hungry.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue!

**Comment by fadhlirahim** [comment]
:+1:

**Comment by Valentine** [comment]
:+1:

**Comment by Valentine** [comment]
Inviting @hyperair since he works around the area sometimes.

**Comment by robertsky** [comment]
Amoy is opened already?

And @hyperair... that depends if he drags himself out of @hackerspacesg in time for work. :stuck_out_tongue:

**Comment by cheeaun** [comment]
@robertsky looks like it's reopened, according to [this guy's tip on Foursquare](https://foursquare.com/item/54fc5c4f498e1169cdc3f7ff) :smile:

**Comment by robertsky** [comment]
I don't believe.  Will walk pass it later to verify.

**Comment by robertsky** [comment]
Ok. It is. ![img_20150310_191011](https://cloud.githubusercontent.com/assets/1820367/6573891/4a571b0e-c75a-11e4-8ca1-69bb12d355ec.jpg)

**Comment by cheeaun** [comment]
@robertsky wow thanks for verifying! :smile:

**Comment by cheeaun** [comment]
This is kinda too impromptu but still, jio-ing @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @ctrlaltreboot @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @laktek @ahkeno @soareschen @renettarenula @dqminh @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @yongfook @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen and anyone!

**Comment by creativepsyco** [comment]
Aiya too busy with fossasia @laktek are you dropping by? I see how

**Comment by robertsky** [comment]
Oh my. If the group is too big, you guys may have to chope seats early.

**Comment by cheeaun** [comment]
@creativepsyco this event is @laktek -special :smiley: 

@robertsky 11:30 not early? :smirk: 

btw, feel free to join our chatroom! https://kopijs.slack.com/

**Comment by yohanesyuen** [comment]
Aku not free. Cya guys at FOSSAsia, whoever's going. :wink:

**Comment by robertsky** [comment]
no. not early enough.

**Comment by stephanfeb** [comment]
How about setting up a Slack.com account for KopiJS ? It might make
arranging these things a little easier than using email :)

**Comment by cheeaun** [comment]
@stephanfeb http://kopijs.herokuapp.com/

**Comment by ardydedase** [comment]
@cheeaun :+1: I work around that area. Thanks!

**Comment by Valentine** [comment]
Inviting @Leto, a FOSSAsia speaker!

**Comment by cheeaun** [comment]
Choped a table near 01-01 stalls

**Comment by winston** [comment]
Sorry! I can't make it today. Anyway, why is it a @laktek special?

**Comment by Valentine** [comment]
Photos!

![Wefie](https://cloud.githubusercontent.com/assets/676061/6613190/fa34cb1a-c8c3-11e4-8fc1-2b1b00ee4013.jpg)
![Being awesome](https://cloud.githubusercontent.com/assets/676061/6613193/007a3618-c8c4-11e4-8533-bc041ff879fb.jpg)

**Comment by cheeaun** [comment]
Everyone, thanks for coming and choping the tables!

Okay now some photos, uh above. Anyone who taken photos please do share.

And the attendees:

- Myself :coffee: 
- @laktek 
- @soareschen
- @ctrlaltreboot
- @fadhlirahim 
- @Valentine 
- @d10
- @hyperair
- @alyssaq
- @eugeneteo
- @meson10
- @dqminh
- anyone else?

Few notes:

- Place starts to get very crowded around 11:35AM. Lots of people who work around that area, go there.
- The chatroom proves to be useful for updating people about the location and changes in plans. Integration with Twitter is a nice touch.
- Some people left abruptly so I have no idea what happened.

Closing the issue now...
