### ISSUE TITLE
KopiJS 13th meetup - 11th April 2015

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#27]
As usual, it's a meetup for kopi lovers where we'll hang out and talk about Kopi, JS and anything.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Saturday, 11 Apr 2015, 11:00AM**
Location: **[My Awesome Cafe](http://www.myawesomecafe.com/)** ([Foursquare](https://foursquare.com/v/my-awesome-cafe-%E7%9C%9F%E6%A3%92%E5%A0%82/52bd3837498e63a584baa251)), [202 Telok Ayer St, 068639 Singapore](https://www.google.com/maps/place/My+Awesome+Cafe/data=!4m2!3m1!1s0x31da190d7b9574f3:0xca3d78e08874f9b1)
[![](http://maps.googleapis.com/maps/api/staticmap?center=202+Telok+Ayer+St,+068639+Singapore&zoom=15&scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xe7862c%7Clabel:K%7C202+Telok+Ayer+St,+068639+Singapore)](https://www.google.com/maps/place/My+Awesome+Cafe/data=!4m2!3m1!1s0x31da190d7b9574f3:0xca3d78e08874f9b1)

*****
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at My Awesome Cafe. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat brunch also can if hungry.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue!

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @ctrlaltreboot @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @laktek @ahkeno @soareschen @renettarenula @dqminh @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @yongfook @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 and anyone!

**Comment by cheeaun** [comment]
Inviting @shortdiv also :smile:

**Comment by sayanee** [comment]
inviting @duykhoa new developer in Singapore. Let's all welcome him :smile:

**Comment by creativepsyco** [comment]
This time in the city? Lau Pa Sat? Hi @duykhoa

**Comment by notthetup** [comment]
Err... The new Lau Pa Sat is more expensive and everyone tells me the food quality dropped.. :(

**Comment by duykhoa** [comment]
Hi all,
Hope to see you there.

P.S. Thanks for inviting me @sayanee.

**Comment by yohanesyuen** [comment]
Thanks for the invite! I should be free! :+1:

**Comment by stuti90** [comment]
Woot! It's in the city! I will join this time :+1: Inviting @rahulparsani to try out a kopijs meetup. :smile:

**Comment by rahulparsani** [comment]
:+1:

**Comment by kahwee** [comment]
:+1:

**Comment by notthetup** [comment]
sorry gang.. super busy today. have fun some good :coffee: for me :)

**Comment by renettarenula** [comment]
Sorry guys. Would love to come but I am sick and want to use the weekend to recuperate.

**Comment by creativepsyco** [comment]
Last minute change of plans. I won't be able to make it @cheeaun :sob:

**Comment by cheeaun** [comment]
Everyone, thanks for coming!

Some photos by @miccheng

![](https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/1012964_10153260605662229_4017198074163395351_n.jpg?oh=45563fc0eee1d85454d330d661691919&oe=559832CC&__gda__=1436899494_b07105d817329a650a597be344ecf718)
![](https://scontent-sin.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11149289_10153260605762229_5197126033566393204_n.jpg?oh=efbc962c3a400d279900dfc23eae446c&oe=5599D5D3)

and more: https://www.facebook.com/miccheng/posts/10153260607237229?pnref=story

And the attendees:

- Myself :coffee: 
- @miccheng
- @duykhoa + 1
- @shortdiv + 1
- @stuti90 
- @rahulparsani 
- @gigablah
- @soulofpeace 
- @kahwee 
- anyone else?

Few notes:

- The place is hipster-ishly chill. Lots of empty seats. Pretty fancy decorations and food menu.
- Owner of My Awesome Cafe emailed me, thanking me for organizing :open_mouth:
- People who don't know me can't figure out which group is the KopiJS peeps. I'm the only one wearing the KopiJS t-shirt. TODO: need better solution for this.

Closing the issue now...

**Comment by sayanee** [comment]
:heart_eyes: :purple_heart: :camera: 

nice learning points @cheeaun - maybe can carry a small kopijs flag :laughing:

**Comment by yohanesyuen** [comment]
Shucks, I just saw this....

**Comment by cheeaun** [comment]
@sayanee better solution would be t-shirts :stuck_out_tongue: 

@yohanesyuen next time then :grin:
