### ISSUE TITLE
KopiJS 14th meetup - 21st May 2015

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#28]
As usual, it's a meetup for kopi lovers where we'll hang out and talk about Kopi, JS and anything.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Thursday, 21 May 2015, 7:30PM**
Location: **[Selfie Coffee](https://instagram.com/selfiecoffeesg)** ([Foursquare](https://foursquare.com/v/selfie-coffee-sg/5540497c498e00717ae85b14), [Facebook](https://www.facebook.com/selfiecoffeesg)), [11 Haji Lane, 189204 Singapore](https://www.google.com.sg/maps/place/%23Selfie+Coffee+Singapore/@1.300427,103.859256,17z/data=!3m1!4b1!4m2!3m1!1s0x0000000000000000:0x04183afd1d2f2205)
[![](http://maps.googleapis.com/maps/api/staticmap?scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:red%7C1.300427,103.859256)](https://www.google.com.sg/maps/place/%23Selfie+Coffee+Singapore/@1.300427,103.859256,17z/data=!3m1!4b1!4m2!3m1!1s0x0000000000000000:0x04183afd1d2f2205)

*****
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Selfie Coffee Cafe. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue!

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @AudreyLim @stuti90 @cbas @alyssaq @serrynaimo @creativepsyco @Valentine @zz85 @miccheng @liuziyi @chenzihui @gigablah @yohanesyuen @ardydedase @laktek @ahkeno @soareschen @renettarenula @honcheng @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @wynlim and anyone!

**Comment by cheeaun** [comment]
Also inviting @ishanagr

**Comment by Valentine** [comment]
:+1:

**Comment by notthetup** [comment]
Will be at http://v.campjs.com/ :(

**Comment by gigablah** [comment]
Kopi at 7:30pm? :+1:

**Comment by ishanagr** [comment]
:+1:

**Comment by stuti90** [comment]
:+1:
7.30 PM can't have Kopi so late T_T but I want to see the selfie coffee in action!

**Comment by llun** [comment]
:+1:

**Comment by creativepsyco** [comment]
:+1:

**Comment by sayanee** [comment]
meeeeee :+1:

**Comment by gigablah** [comment]
Inviting @leongkui @ruckuus @jmrocela

**Comment by stuti90** [comment]
Something came up last minute :( Sorry won't be able to make it for this one. Please share all the coffee selfies!

**Comment by ahkeno** [comment]
coming :)

**Comment by cheeaun** [comment]
@stuti90 :sob:
@ahkeno :+1:

**Comment by miccheng** [comment]
Ok. I'll be there.

**Comment by cheeaun** [comment]
Everyone, thanks for coming and taking selfies!

Some photos:
![](https://scontent-sin1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/13277_10153353568412229_6896276323413927815_n.jpg?oh=5c7263df8b356e8c14a278cc2608e55c&oe=55CDA673)
![](https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xta1/v/t1.0-9/11351260_10153353568702229_3638055791741939738_n.jpg?oh=237dbcf83ff1a97940b855585df76b48&oe=5603D6FD&__gda__=1442532016_5543f96675ac3cf89d7956c2b1d6ecb7)
![](https://scontent-sin1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/10731112_10153353999307229_7986669441079346022_n.jpg?oh=3cf4d6bfd07999820befa53f41e099c1&oe=55F76002)

And more!

- The NEW Flickr Group! https://www.flickr.com/groups/kopijs/
- https://www.facebook.com/photo.php?fbid=10155564831015557&set=a.10151128009495557.800129.571810556&type=1
- https://www.facebook.com/miccheng/posts/10153353527217229
- https://www.facebook.com/miccheng/posts/10153353568847229
- https://www.facebook.com/miccheng/posts/10153354001747229
- http://iconosquare.com/tag/kopijs
- and few more from @Valentine 's camera

And the attendees...:

- Myself :camera: :coffee: 
- @miccheng 
- @liuziyi
- @sayanee 
- @Valentine 
- @creativepsyco 
- @gigablah 
- @llun 
- @ishanagr 
- @chernjie
- anyone else?

Few notes:

- The place is pretty small but at least have 2nd floor to accommodate more people. It's said to have more people going there during weekends so lucky we go there in the evening on a weekday.
- I forgot to wear the KopiJS t-shirt, but doesn't seem to matter anyway, especially when we're hanging out in the 2nd floor where people can't see me from outside.
- Having a meetup in the evening have this usual dilemma of having dinner *before* OR *after* the meetup.

Closing the issue now...

**Comment by sayanee** [comment]
:sparkling_heart: :tada: :coffee:

**Comment by cheeaun** [comment]
One more photo from the Selfie Coffee folks! https://instagram.com/p/3CNTEWn2Pz/
