### ISSUE TITLE
KopiJS 15th meetup - 18th July 2015 - Raya special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#29]
As usual, it's a meetup for kopi lovers where we'll hang out and talk about Kopi, JS and anything.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Saturday, 18 July 2015, 11:00AM**
Location: **[Oberstrasse](https://www.facebook.com/oberstrasse)** ([Foursquare](https://foursquare.com/v/oberstrasse/54dc656f498e085d40a1c141)), [Blk 809 French Road #01-50, Singapore 200809<br>![](http://maps.googleapis.com/maps/api/staticmap?scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1EhKQfZ.png%7Cshadow:false%7C809+French+Rd,+Singapore)](https://www.google.com.sg/maps/place/Oberstrasse/@1.308327,103.8621767,17z/data=!3m1!4b1!4m2!3m1!1s0x31da19c9f734660f:0x9c91fd127568ec0b)

*****
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Oberstrasse. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @laktek @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa @rahulparsani @ishanagr @leongkui @ruckuus @jmrocela @chernjie @llun and anyone!

**Comment by MarkFull** [comment]
:+1:

**Comment by nathaniawong** [comment]
:neckbeard:

**Comment by cliener** [comment]
:+1:

**Comment by Valentine** [comment]
:+1:

**Comment by cheeaun** [comment]
Also inviting @rahulparsani @ishanagr @leongkui @ruckuus @jmrocela @chernjie @llun

**Comment by llun** [comment]
French road! :smirk: 

:+1:

**Comment by miccheng** [comment]
Will be there!

**Comment by creativepsyco** [comment]
Oops wont be in SG during that time :cry:

**Comment by renettarenula** [comment]
Unfortunately, I can't come. :( 
It is Hari Raya. I have a family gathering.

**Comment by cheeaun** [comment]
@renettarenula :cry: Happy Raya! :smile:

**Comment by cheeaun** [comment]
Inviting @yuhui

**Comment by jin** [comment]
+1

**Comment by sayanee** [comment]
:+1:

**Comment by duykhoa** [comment]
:100:

**Comment by astralwave** [comment]
👍

**Comment by duykhoa** [comment]
Sorry guys, in last minute my friends visit me from Friday.

Will join you guys next meetup :crying_cat_face:

**Comment by miccheng** [comment]
:+1:

**Comment by yohanesyuen** [comment]
:+1:

**Comment by cheeaun** [comment]
Everyone, thanks for coming and eating brunches!

Some photos:
![](https://scontent-sin1-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11223970_10153518057987229_4799857490291146491_n.jpg?oh=878074a57398c37683c9ccacd9cd9dcc&oe=5651F089)
![](https://scontent-sin1-1.xx.fbcdn.net/hphotos-xtp1/v/t1.0-9/11144996_10153518044767229_935799319306818062_n.jpg?oh=c8c231056121551bcb0e91923aaf0d35&oe=561848BF)

And more!

- https://www.facebook.com/miccheng/posts/10153518044947229
- https://www.facebook.com/photo.php?fbid=10153518057987229&set=a.475431307228.261529.503517228&type=1
- https://twitter.com/coderkungfu/status/622280774616788992
- some photos coming up by @kaihendry
- some photos coming up by @Valentine too

And the attendees...:

- Myself :coffee:
- @miccheng 
- @MarkFull 
- @llun 
- @nathaniawong 
- @Valentine 
- @ishanagr
- @chernjie
- @kaihendry
- @cbas
- @liuziyi
- @serrynaimo
- @yohanesyuen
- @soareschen
- @jin 
- @sayanee 
- @notthetup
- @mgajda (?)
- vi (dunno the GitHub account)
- anyone else?

Few notes:

- The place is quite small and the staff were very accommodating to us since we take up so many tables and chairs. Some of the other customers also gave in to our larger group.
- I think some of us, especially @nathaniawong, felt awkward during the meetup, so I'll need to do a better job for new people joining.
- Having the meetup near Hackerspace.SG seems pretty convenient.

Closing the issue now...

**Comment by jin** [comment]
Thank you @cheeaun!

**Comment by nathaniawong** [comment]
Lol thanks @cheeaun for the mention (⌒_⌒;) and organising this!

**Comment by cheeaun** [comment]
One more photo by @kaihendry ! https://www.flickr.com/photos/hendry/19607439259/

**Comment by fmap** [comment]
> vi (dunno the GitHub account)

hi

**Comment by yohanesyuen** [comment]
Inviting @hqtan94 for the next meetup! :D
