### ISSUE TITLE
KopiJS 16th meetup - 29th August 2015

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#30]
As usual, it's a **casual meetup** for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are **not required**.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Saturday, 29 August 2015, 11:00AM**
Location: **[Yahava KoffeeWorks](http://www.yahava.sg/)** ([Foursquare](https://foursquare.com/v/yahava-koffeeworks/4e26993bd4c007d41a94039a)), [4 Jln Gelenggang, Singapore 578188<br>![](http://maps.googleapis.com/maps/api/staticmap?autoscale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1EhKQfZ.png%7Cshadow:false%7CYahava+KoffeeWorks,+4+Jln+Gelenggang,+Singapore+578188)](https://www.google.com.sg/maps/place/Yahava+KoffeeWorks+(Singapore)/@1.3731067,103.8298525,17z/data=!4m2!3m1!1s0x31da16d1d14dd295:0x3e540b9a8a8c8cd0)

*****
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Yahava Koffeeworks. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @laktek @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa @rahulparsani @ishanagr @leongkui @ruckuus @jmrocela @chernjie @llun

Those joining, feel free to invite your friends!

**Comment by cheeaun** [comment]
+ inviting @rahulparsani @ishanagr @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap

**Comment by sayanee** [comment]
:+1: of course i'm going!!!! :dancer:

**Comment by notthetup** [comment]
lol!

**Comment by yohanesyuen** [comment]
Inviting @hqtan94

**Comment by creativepsyco** [comment]
will be there :boom:

**Comment by gigablah** [comment]
:+1:

**Comment by hqtan94** [comment]
thanks @yohanesyuen,
sms me when you are free weiping, my phone broke down don't have whatsapp liao..

**Comment by maziyyahjaf** [comment]
![image](https://cloud.githubusercontent.com/assets/13558622/9319826/79d4af00-4585-11e5-913c-657d223b3485.png)

**Comment by jpibarra1130** [comment]
@yusryh

**Comment by kahwee** [comment]
I'll have to give this a miss. :(

Have fun!

**Comment by cheeaun** [comment]
@kahwee :sob: next time then!

**Comment by burnflare** [comment]
Will be there!

**Comment by cheeaun** [comment]
@burnflare :+1: finally!

**Comment by ksaitor** [comment]
I don't always :+1: , but when I do, I also add to my Google Cal. ;)

**Comment by cheeaun** [comment]
@ksaitor :+1: :calendar:

**Comment by jin** [comment]
:+1: :wink:

**Comment by MarkFull** [comment]
:+1:  inviting @Kiza

**Comment by yohanesyuen** [comment]
:+1:

**Comment by cliener** [comment]
:+1: IRL FTW

**Comment by cheeaun** [comment]
@cliener 🙌

**Comment by wizztjh** [comment]
Quite far away from my place! Will try my best to come. :+1:

**Comment by llun** [comment]
:+1:

**Comment by cheeaun** [comment]
Everyone, thanks for coming!

Some photos:

![](https://farm1.staticflickr.com/608/20951976836_984a4baab4_h.jpg)

And some by @miccheng https://twitter.com/coderkungfu/status/637467620996874240

This time we have an audio recording by @kaihendry: http://s.natalian.org/2015-08-29/kopiJS16.mp3 :loud_sound: 

And the attendees:

- Myself :coffee: 
- @miccheng
- @kaihendry
- @jpibarra1130 
- @yusryh
- @sayanee 
- @notthetup 
- @jin 
- @MarkFull 
- @llun 
- @ksaitor 
- @cbas
- @alyssaq
- @cliener (?)
- anyone else?

Few notes:

- Pretty nice place, but too far from any MRT stations. 3G/4G connections inside is pretty bad so perhaps, more talking, less *interneting*?
- Clashes with Rails Girls meetup :cry: 
- Next time need to clarify to (new) attendees that there are **no** reservations done at the coffee place.

Closing the issue now...

**Comment by nathaniawong** [comment]
- Clashing with Rails Girls :sob: Dem feels bro... Hope you all had a good one!
