### ISSUE TITLE
KopiJS 17th meetup - 4th October 2015 - @laktek -special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#31]
As usual, it's a **casual meetup** for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are **not required**.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Sunday, 4 October 2015, 5:30PM**
Location: **[Percolate](http://percolate.sg/)** ([Foursquare](https://foursquare.com/v/percolate/5324821311d2391c01c3400f)), [136 Bedok North Avenue 3 #01-152B, Singapore 460136](https://www.google.com.sg/maps/place/Percolate/@1.328263,103.935139,17z/data=!3m1!4b1!4m2!3m1!1s0x31da3d4af8c3a157:0xe3ac03d1ecd8178e)

*****
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd](http://lanyrd.com/series/kopijs/).
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

*****

##### Agenda

1. Gather at Percolate. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).

**RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
So @laktek will be in SG for a very short while, this will be a chance to meet and greet him in person.

:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @Valentine @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa

Those joining, feel free to invite your friends!

**Comment by cheeaun** [comment]
Also inviting @rahulparsani @ishanagr @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap @ksaitor @jin @cliener @wizztjh

**Comment by winston** [comment]
Sorry can't do it on 4th Oct! :(

**Comment by notthetup** [comment]
:scream: It's @laktek IRL!

**Comment by ksaitor** [comment]
👍🏻

**Comment by ksaitor** [comment]
wait… 5:30PM? It's like almost dinner time?!
y no morning / afternoon?

**Comment by jin** [comment]
:+1:

**Comment by cheeaun** [comment]
@ksaitor because that's the only time we can see @laktek 😭

**Comment by mgajda** [comment]
ok!
>
>

-- 
  Pozdrawiam
    Michał

**Comment by yohanesyuen** [comment]
:+1:

**Comment by yohanesyuen** [comment]
Inviting @hqtan94

**Comment by laktek** [comment]
I got some TimTams. Don't miss out! https://files.slack.com/files-pri/T024HV01E-F0BQCHWCF/slack_for_ios_upload.jpg

**Comment by laktek** [comment]
I got some TimTams. Don't miss out! 
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/5358/10262634/15022a72-6a14-11e5-8f50-a67df0693171.jpg)

**Comment by miccheng** [comment]
OMG!!!! YES!!!

**Comment by zz85** [comment]
Sorry laktek, I will miss you again! Have a great meet 😃

**Comment by valentine** [comment]
:+1:

**Comment by cheeaun** [comment]
Everyone, thanks for coming!

Some photos:

[![](https://pbs.twimg.com/media/CQeQAxiWcAAQ-iy.jpg)](https://twitter.com/Valentine/status/650647014380847104)

Some by @miccheng : https://www.facebook.com/miccheng/posts/10153708182877229

And.. few more by @valentine 's special camera 😏

And the attendees:

- Myself :iphone: :coffee: 
- @miccheng 
- @sayanee
- @notthetup 
- @ksaitor 
- @cbas
- @alyssaq
- @serrynaimo
- @liuziyi
- @valentine 
- @audreylim
- @yinshanyang
- @tensaix2j
- @pasindud
- 3 more person who I forgot the name :sob: 
- anyone else?

Few notes:

- The place is okay, but kind of hard to find especially after getting off from the MRT station (Bedok).
- First timers still have that awkward feeling, so will need to fix that.
- @laktek couldn't make it unfortunately :sob: :sob: :sob:

Closing the issue now...

**Comment by ardydedase** [comment]
I was there! :)

**Comment by cheeaun** [comment]
@ardydedase lol sorry, added :smile:

**Comment by pasindud** [comment]
:+1:

**Comment by yangzai** [comment]
🙋

**Comment by cheeaun** [comment]
@yangzai oops, added :smile:

**Comment by tjjjwxzq** [comment]
I'm supposedly "Jun Qi" XD

**Comment by cheeaun** [comment]
@tjjjwxzq thanks, updated ^ :smile:
