### ISSUE TITLE
KopiJS 18th meetup - 31st October 2015 - @laktek -special #2

### ISSUE THREAD

**Issue by valentine** [KopiJS/kopi.js#32]
As usual, it's a **casual meetup** for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are **not required**.

Website: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Saturday, 31 October 2015, 6:30PM**
Location: **Chin Chin Eating House** ([Foursquare](https://foursquare.com/v/chin-chin-eating-house/4b0eb596f964a520ea5923e3)), 19 Purvis Street, Singapore 188598
(possible alternate location: YY Kafei Dian ([Foursquare](https://foursquare.com/v/yy-kafei-dian-%E5%96%9C%E5%9B%AD%E5%92%96%E5%95%A1%E5%BA%97/4b25a5f0f964a520f47424e3)), 37 Beach Road (Purvis Street), 189678)

---

# SUPER IMPORTANT

* [**SUBSCRIBE** to the event via Lanyrd.](http://lanyrd.com/series/kopijs/)
* [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
* **SUBSCRIBE** to this issue for updates.

---

##### Agenda

1. Gather at Chin Chin. Chope some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)). If Chin Chin is really crowded, we'll be at YY Kafei Dian down the same road.
2. Drink Kopi/Teh/Milo/whatever. [Eat also can](http://ieatishootipost.sg/chin-chin-resurrection-of-an-old-hainanese-instituition/) if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

* No free food/drinks/goodies provided. Remember bring your money.
* [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096) (:sweat_smile:)
* If you're lost, DM/tweet [@valentinechua](https://twitter.com/valentinechua).

**RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by valentine** [comment]
Our second attempt to meet @laktek, who will be in Singapore for the evening. Come eat chicken rice with us!

:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa

Those joining, feel free to invite your friends!

**Comment by valentine** [comment]
Also inviting @rahulparsani @ishanagr @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap @ksaitor @jin @cliener @wizztjh @yinshanyang
@hqtan94 @pasindud @ardydedase @yangzai @christabella

**Comment by notthetup** [comment]
:boom:

**Comment by fmap** [comment]
:droplet: :droplet: :droplet: :droplet: :droplet:

**Comment by joerx** [comment]
Lanyrd event is on Oct. 4th?

**Comment by wizztjh** [comment]
:+1:

**Comment by yangzai** [comment]
:+1:

**Comment by valentine** [comment]
It's happening later. Don't say bo jio!

**Comment by pasindud** [comment]
:+1:

**Comment by yangzai** [comment]
chilling @ killiney across the st

**Comment by yangzai** [comment]
chin chin looks crowded

**Comment by valentine** [comment]
We're at YY Kafei Dian two units down!

**Comment by Learnemy** [comment]
Are you all still there 30mins later?

**Comment by miccheng** [comment]
Gone. :(

**Comment by laktek** [comment]
Here's photo proof that I was there (and we had TimTams):

![11221473_10156093538420618_7268428045047905848_n](https://cloud.githubusercontent.com/assets/5358/10892407/5643e610-81f7-11e5-99d2-931af7c569e6.jpg)
![12190843_10153104098746781_6781040996906335580_n](https://cloud.githubusercontent.com/assets/5358/10892408/56472b0e-81f7-11e5-830f-e2fe92a0a27d.jpg)

attendees:
* myself (@laktek)
* @valentine 
* @pasindud 
* @miccheng 
* @yangzai 
* @danishka
* @joerx

**Comment by cheeaun** [comment]
:+1:

**Comment by joerx** [comment]
(y)

**Comment by pasindud** [comment]
:+1:
