### ISSUE TITLE
KopiJS 19th meetup - 22nd November 2015 - DevFest.Asia edition

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#33]
This is a casual meetup for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are not required.

This time is a special edition, being part of [DevFest.Asia 2015](http://2015.devfest.asia/).

**Learn more** about this meetup: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Sunday, 22 November 2015, 11:00AM**
Location: [**Ya Kun Kaya Toast**](https://foursquare.com/v/ya-kun-kaya-toast-%E4%BA%9E%E5%9D%A4/4b231bc2f964a520635324e3), [18 China St #01-01 Singapore 049560](https://www.google.com.sg/maps/place/Ya+Kun+Kaya+Toast,+18+China+St,+Singapore+049560/@1.283737,103.84788,17z/data=!4m2!3m1!1s0x31da190c639bfa6f:0xc2d759952fbf4687)
Nearby MRT stations: Telok Ayer (blue line), Raffles Place (red, green), Chinatown (blue, purple)
[![](http://maps.googleapis.com/maps/api/staticmap?center=18+China+St,+Singapore&zoom=16&scale=2&size=640x320&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1EhKQfZ.png%7Cshadow:true%7C18+China+St,+Singapore)](https://www.google.com.sg/maps/place/Ya+Kun+Kaya+Toast,+18+China+St,+Singapore+049560/@1.283737,103.84788,17z/data=!4m2!3m1!1s0x31da190c639bfa6f:0xc2d759952fbf4687)
[Get directions :earth_asia:](https://www.google.com/maps/dir/Current%20Location/Ya%20Kun%20Kaya%20Toast%2C%2018%20China%20St%20%2301-01%20Singapore%20049560)

---
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd.](http://lanyrd.com/series/kopijs/)
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

---

##### Agenda

1. Gather at Ya Kun. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).
- Usually the owner of the coffee place isn't aware of the meetup so don't ask him/her about it.
- I (@cheeaun) [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk). I'm also the guy in the pool table photo of "DevFest.Asia Welcome Party" on [DevFest.Asia page](http://2015.devfest.asia/) 😎

Optional: **RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
Ping @coderkungfu for advice on the perfect location 😄

Also ping @serrynaimo

**Comment by serrynaimo** [comment]
let me know whenyou knowwhich ya kun :(

**Comment by serrynaimo** [comment]
woah, halfasleep on mobile... missed the right smiley ;)

**Comment by cheeaun** [comment]
@serrynaimo location has been set 👍 👆

**Comment by serrynaimo** [comment]
:)

**Comment by hydrospell** [comment]
Do you rsvp by just posting " :+1:" or am I missing a really obvious button somewhere?

**Comment by cheeaun** [comment]
@hydrospell technically you can rsvp here https://www.eventnook.com/event/devfestasia2015/home or 👍 here but feel free to join anyway 😁 This is a very casual meetup with no yes/maybe/no confirmation. Just join when you're free 👌

**Comment by hydrospell** [comment]
good stuff 👌

**Comment by m19** [comment]
I will be joining :+1:

**Comment by joerx** [comment]
+1

**Comment by jin** [comment]
:+1:

**Comment by cheeaun** [comment]
Those who have reach the Ya Kun place or got lost or couldn't find me, please ping me in the Slack chat room 👍

There's no point asking the owner or servers of the place because they have no idea about the meetup 😜

**Comment by cheeaun** [comment]
Everyone, thanks for coming.

Photos:

![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/2296/11328253/a128798c-91c1-11e5-8c97-fc34d3d32a6a.jpg)
![](https://pbs.twimg.com/media/CUYu6tGU8AAXJud.jpg:large)

Tweets:

- https://twitter.com/devfestasia/status/668273204788486145
- https://twitter.com/cheeaun/status/668260125866598400
- https://twitter.com/hj_chen/status/668317439503921152

And the attendees:

- Myself :coffee: :sunglasses: 
- @ksaitor
- @serrynaimo 
- @m19 
- @jin 
- @fadhlirahim 
- @yangzai
- @nv
- @zellwk
- @llun
- @markfull
- @melvinzhang
- @huijing
- @jurvis
- @jennz0r
- @zaizhuang
- @joerx
- 'zachc'
- if I'm not mistaken, one more guy who I forgot to ask the name :man: 
- anyone else?

Few notes:

- Turns out to be the most "official" meetup ever, with the DevFest.Asia banner and badge scanning :alien: 
- The place again proves to be pretty good and has plenty of space, even though they sort of "close" the outside area at 2:30PM :space_invader: 
- It rained around 8 or 9AM but luckily stopped raining by the time the meetup runs, so it's good news though it became quite humid during the meetup :sun_with_face: 
- Looks like some people never actually look at the kopijs.org web site and just attend anyway, so need better marketing on that part :sparkles: 
- Looks like no one knows that I'm the organizer so need to work on that part too :no_mouth: 
- Looks like still got people thought KopiJS is only for people who work with JS, but actually not, so need to work on that part also :muscle: 
- Stickers are running out so will need to print more :slot_machine: 
- Looks like demand for Kopi.JS t-shirts are getting too damn high so will need to find a sponsor soon :shirt: 
- Looks like some people don't know [how to eat soft-boiled eggs](https://www.youtube.com/watch?v=v0Y5VVxpq_A) so... SoftBoiledEggs.JS coming soon? :egg: 

Finally thanks @devfestasia for organizing the best array of events ever in Singapore :+1: 

Closing the issue now...
