### ISSUE TITLE
KopiJS 20th meetup - 16 January 2016

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#34]
This is a **casual social meetup** for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are **not required**.

**Learn more** about this meetup: http://kopijs.org/
Chatroom: **INVITE YOURSELF HERE** http://kopijs.herokuapp.com/
Date: **Saturday, 16 January 2016, 11:00AM**
Location: [**Revelry**](https://www.facebook.com/revelrysg/) ([Foursquare](https://foursquare.com/v/revelry/545e0284498ed803ac4787da)), [#01-02, 21 Lorong Kilat, 598123](https://www.google.com.sg/maps/place/Revelry/@1.3409163,103.7709161,17z/data=!3m1!4b1!4m2!3m1!1s0x31da106227d93aa9:0xc6f6ad93430fba4e)
Nearby MRT station: [:haircut:  **Beauty World** :nail_care:](https://en.wikipedia.org/wiki/Beauty_World_MRT_Station) on **Downtown 2 line**
[![](http://maps.googleapis.com/maps/api/staticmap?center=21+Lorong+Kilat&zoom=12&scale=2&size=600x500&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1EhKQfZ.png%7Cshadow:true%7C21+Lorong+Kilat
)](https://www.google.com.sg/maps/place/Revelry/@1.3409163,103.7709161,17z/data=!3m1!4b1!4m2!3m1!1s0x31da106227d93aa9:0xc6f6ad93430fba4e)

---
# SUPER IMPORTANT

- [**SUBSCRIBE** to the event via Lanyrd.](http://lanyrd.com/series/kopijs/)
- [**SUBSCRIBE** to iCal here](https://www.google.com/calendar/ical/dnhunu42fotmefouusg4j8ip0k%40group.calendar.google.com/public/basic.ics) for event updates.
- **SUBSCRIBE** to this issue for updates.

---

##### Agenda

1. Gather at Revelry. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).
- Usually the owner of the coffee place isn't aware of the meetup so don't ask him/her about it.
- I (@cheeaun) [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎

Optional: **RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @stuti90 @yeouchien @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa @rahulparsani @ishanagr

Those joining, feel free to invite your friends!

**Comment by cheeaun** [comment]
Also inviting @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap @ksaitor @jin @cliener @wizztjh @yinshanyang @hqtan94 @pasindud @yangzai @christabella  @joerx @Learnemy @danishka @timoxley and oh gosh who else

**Comment by winston** [comment]
Will try to come for this one. @cheeaun Maybe you want to create a team, and add those accounts? Then you just have to ping the team?

**Comment by cheeaun** [comment]
@winston :+1: trying that now. Still have to input everything :sob:

**Comment by winston** [comment]
At least it's just once. Haha.

**Comment by sayanee** [comment]
+1 to what @winston said :smiley: DRY

**Comment by cheeaun** [comment]
I need an 'Add all from this issue to team' button :sob:

**Comment by sayanee** [comment]
chrome extension!! build it build it :ship: :shipit:

**Comment by jurvis** [comment]
👍

**Comment by yangzai** [comment]
:thumbsup:

**Comment by yuhui** [comment]
Will try to attend this time

**Comment by joerx** [comment]
+1

**Comment by Learnemy** [comment]
+1 yay!

**Comment by ksaitor** [comment]
cc @romanzolotarev

**Comment by gigablah** [comment]
:+1:

**Comment by jin** [comment]
:+1:

**Comment by wizztjh** [comment]
:+1: I plan to cycle from Tanjung Pagar/ Outram park along the green corridor (old KTM railway). Who's joining me? :bicyclist:

**Comment by cheeaun** [comment]
@wizztjh hmm sounds interesting...

- http://www.thegreencorridor.org/tag/green-corridor-map/
- https://foursquare.com/user/234324/list/the-green-corridor-rail-corridor
- https://www.google.com/maps/d/viewer?mid=zm-k4-KgqwoA.k9gUwceJLAk8&hl=en_US

**Comment by MarkFull** [comment]
@cheeaun :+1: 
@wizztjh :+1:

**Comment by wizztjh** [comment]
Will start my journey 9.30 am from  The Old Place food court. Tweet to me if you are joining @wizztjh https://www.google.com.sg/maps/place/The+Old+Place+Food+Court/@1.2770201,103.8306322,18z/data=!4m7!1m4!3m3!1s0x31da1964f4b6f609:0x1c984f954783fde1!2sSilat+Rd!3b1!3m1!1s0x0000000000000000:0x17f37df70d047a46

**Comment by robertsky** [comment]
Bah... On road bike, I guess I give the cycling portion a miss.

**Comment by creativepsyco** [comment]
:+1: will join this time for sure :)

**Comment by kahwee** [comment]
Have fun guys! Tell me if anyone's going to San Francisco soon! :D

**Comment by yuhui** [comment]
can't attend again

**Comment by cheeaun** [comment]
@yuhui 😩

**Comment by arunthampi** [comment]
will be in singapore, :+1:

**Comment by cheeaun** [comment]
@arunthampi 😱👍😎

**Comment by miccheng** [comment]
Is anyone else as confused as me with the 20th meetup on the 16th? :p

**Comment by cheeaun** [comment]
@miccheng lol never actually thought about that. Now that you mention it, it becomes confusing :confounded:

s/16th/16 :stuck_out_tongue:

**Comment by robertsky** [comment]
Would not be able to attend due to meetings.

**Comment by cheeaun** [comment]
@robertsky 😩

**Comment by serrynaimo** [comment]
Can I hijack that KopiJS to lay out a rough plan for DevFest this year? :) Starting a bit earlier this time and would love to have the community even more involved in JSConf/CSSConf this year. We want to make the event a bit bigger this time around.

**Comment by cheeaun** [comment]
@serrynaimo sure! Remember to bring stickers 😉

**Comment by kahwee** [comment]
How about about KopiJS v20, shipped with Semver goodness.

**Comment by winston** [comment]
Sorry @cheeaun Think I can't make it le. :(

**Comment by cheeaun** [comment]
@winston 😩

**Comment by cheeaun** [comment]
Everyone, thanks for coming!!

Photo:
![](http://c2.staticflickr.com/2/1620/24120317440_17aeb61e2e_z.jpg)

More:
- https://www.flickr.com/photos/cheeaun/24415937915/in/pool-kopijs/
- https://www.flickr.com/photos/cheeaun/24048116089/in/pool-kopijs/
- https://www.flickr.com/photos/cheeaun/23789171923/in/pool-kopijs/

And the attendees:

- Myself :coffee: 
- @staceytay
- @gigablah 
- @serrynaimo 
- @yangzai
- @wizztjh 
- @cbas
- @alyssaq
- @MarkFull 
- @ongmin
- @jsstrn
- @jin 
- @ardydedase
- @jurvis 
- @joerx 
- @tongrhj
- @sevresbabylone
- @AlvinderSingh
- @mgajda
- one more guy if I'm not mistaken?
- anyone else?

Few notes:

- Turns out that most people cycle, ride bike, walk or take bus instead of taking the train to Beauty World MRT Station :grin: 
- Place is very nice and quite empty with nice atmosphere and plenty of space :+1: 
- Seems like some people ( [@ahkeno](https://twitter.com/ahkeno/status/688244995699036160) and @miccheng ) got confused with the issue title, thinking that it's 20th Jan instead of 16th. Will need to readjust the title format for next one :thought_balloon: 
- #kopijs stickers are srsly running out, have to print more. Including the pixelated one :star2: 

Closing the issue now...
