### ISSUE TITLE
KopiJS 21st meetup - Monday, 1 February 2016 - @rauchg -special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#35]
This is a **casual social meetup** for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are **not required**.

Date: **Monday, 1 February 2016, 6:30PM**
Location: **[Palette](http://www.thepalette.com.sg/)** ([Foursquare](https://foursquare.com/v/palette/55a9dc64498e3f6ace18ca83)) ([Facebook](https://www.facebook.com/ThePaletteSingapore))
Address: [13 Stamford Road, Capitol Piazza #B1-20/27, Singapore 178905 ![](http://maps.googleapis.com/maps/api/staticmap?center=13+Stamford+Road,+Singapore&zoom=17&scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1EhKQfZ.png%7Cshadow:true%7C13+Stamford+Road,+Singapore)](https://www.google.com.sg/maps/place/Palette+Restaurant+%26+Bar/@1.2929668,103.8515422,15z/data=!4m2!3m1!1s0x0:0x3c20bdce0f859cb7)

##### Agenda

1. Gather at the Palette. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) some tables. Ping everyone in the [chatroom](https://kopijs.slack.com/) ([Join here](https://kopijs.herokuapp.com/)).
2. Drink Kopi/Teh/Milo/whatever. Eat also can if hungry. Exchange stickers if you have them.
3. Hang out like the cool kids and take group selfies.

##### Notes

- No free food/drinks/goodies provided. Remember bring your money.
- [Got free stickers!](https://twitter.com/cheeaun/status/545045379738116096)
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).
- Usually the owner of the place isn't aware of the meetup so don't ask him/her about it.
- I (@cheeaun) [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎

Optional: **RSVP** by :+1:-ing this issue! If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by rauchg** [comment]
+1 Thanks @cheeaun for putting this together!

**Comment by joerx** [comment]
+1

**Comment by fadhlirahim** [comment]
+1

**Comment by cbas** [comment]
Venue somewhere CBD? Where is convenient for @rauchg ?

**Comment by cheeaun** [comment]
Okay so far, we have these as candidates:

1. [Ya Kun Kaya Toast](https://foursquare.com/v/ya-kun-kaya-toast-%E4%BA%9E%E5%9D%A4/4b231bc2f964a520635324e3) as suggested by me and @notthetup
2. [Blue Ginger](https://foursquare.com/v/the-blue-ginger-restaurant/4b058812f964a520e9af22e3) - more [*atas*](http://www.urbandictionary.com/define.php?term=Atas) place, suggested by the more *atas* @notthetup
3. [Lau Pa Sat](https://foursquare.com/v/lau-pa-sat-festival-market/4b13fe99f964a520659b23e3), kind of what I was thinking as a local (also tourist-y) place to indulge yummy local food.

**Comment by rauchg** [comment]
@cbas I'm really flexible! Haven't seen much yet so looking forward to wherever you all choose.

**Comment by cheeaun** [comment]
@cbas any place you have in mind? :thought_balloon:

**Comment by cbas** [comment]
@cheeaun I like [Palette](https://foursquare.com/v/palette/55a9dc64498e3f6ace18ca83). It is what all food courts should be like: delicious, pleasant, modern, affordable. I'm sure it's also atas enough for @notthetup.

**Comment by cheeaun** [comment]
@cbas ok deal, we'll settle with Palette :+1: /cc @rauchg

**Comment by rauchg** [comment]
Awesome. Will most likely get there around 7pm. Thank you

**Comment by cheeaun** [comment]
@rauchg sure :smile: I just set earlier because statistically speaking, people will be late anyway :stuck_out_tongue:

**Comment by jianw3i** [comment]
+1

**Comment by joerx** [comment]
+1

**Comment by neeravkumar** [comment]
+1

**Comment by cheeaun** [comment]
@joerx you +1 twice? :scream:

**Comment by paradite** [comment]
:+1:

**Comment by yangzai** [comment]
:+1:

**Comment by joerx** [comment]
One for the venue

**Comment by cheeaun** [comment]
Everyone, thanks for coming!

Photos:
[![](https://scontent-sin1-1.xx.fbcdn.net/hphotos-xaf1/t31.0-8/12657901_10156378594135618_1733139803651300041_o.jpg)](https://www.facebook.com/photo.php?fbid=10156378594135618&set=a.253367320617.291573.504105617&type=3&permPage=1)

and a few more...

- https://www.facebook.com/vchua/posts/10156378596360618?comment_id=10156379769955618 <- @rauchg 's face
- https://twitter.com/cheeaun/status/694114193335685120
- https://twitter.com/valentine/status/694130747590995968 (private)
- https://twitter.com/valentinechua/status/694187711373131776
- https://www.facebook.com/photo.php?fbid=10153362585533302&set=a.23776458301.34836.724118301&type=3&theater (private)

And the attendees:

- Myself :coffee: 
- @rauchg 
- @soareschen
- @valentine
- @neeravkumar 
- @markfull
- @joerx 
- @cbas 
- @alyssaq
- @jianw3i 
- @zz85
- @hboon
- @yangzai 
- @paradite 
- @dexxtan
- @jsstrn
- @ongmin
- @caalberts
- @shawnlimws
- @wytanj
- anyone else?

Few notes:

- The place this time is interestingly "atas" tho' spacious enough and not crowded. No free seating and no split bills but still okay :arrow_up: Thanks @jsstrn for "booking" the tables.
- Looks like #kopijs works well as an ad-hoc people-visiting-from-overseas kind of meetup. Perhaps should start advertising it as that kind of event and encourage peeps to use this branding :sparkle: 
- The new stickers work well somehow, so now awaiting for the new pixelated ones to be used in next meetup :grin: 
- Seems like I need to devise a plan to rotate people's seat around tables when there are too many people in the meetup :rotating_light: :thought_balloon: 

Closing the issue now...
