### ISSUE TITLE
KopiJS 22nd meetup - Saturday, 12 March 2016 - Ekochamber-special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#36]
This is a **casual social meetup** for developers and designers in Singapore. We hang out together and talk about Kopi, JavaScript and anything. Knowledge of Kopi and Javascript are **not required**.

Date: **Saturday, 12 March 2016, 11:00AM**
Location: [**Whisk & Paddle**](http://whiskandpaddle.com.sg/) ([Foursquare](https://foursquare.com/v/whisk--paddle/5454a5a7498ee281f02f63ca)) ([Facebook](https://www.facebook.com/whiskandpaddlecafe)), [10 Tebing Lane, 828836 ![](http://maps.googleapis.com/maps/api/staticmap?center=10+Tebing+Lane,+828836&scale=2&zoom=12&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=icon:http://i.imgur.com/1I7mU1l.png%7Cshadow:false%7C10+Tebing+Lane,+828836)](https://www.google.com.sg/maps/place/Whisk+%26+Paddle/@1.393374,103.917762,15z/data=!4m2!3m1!1s0x0:0xb68e0ac0cc3633da)

##### Agenda

Gather there. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) tables. Drink/eat Kopi/whatever. Exchange stickers. Take group selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, DM/tweet [@cheeaun](https://twitter.com/cheeaun).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- I (@cheeaun) [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎

Optional: **RSVP** by :+1:-ing this issue or go to <https://meetapp.co/e/224393>.

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @stuti90 @yeouchien @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa @rahulparsani @ishanagr

Those joining, feel free to invite your friends!

**Comment by cheeaun** [comment]
Also inviting @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap @ksaitor @jin @cliener @wizztjh @yinshanyang @hqtan94 @pasindud @yangzai @christabella  @joerx @Learnemy @danishka @timoxley @tjjjwxzq @AlvinderSingh @sevresbabylone @tongrhj @jsstrn @ongmin @staceytay @jurvis @wytanj @shawnlimws @caalberts @dexxtan @paradite @hboon @jianw3i @neeravkumar and oh gosh who else

**Comment by cliener** [comment]
Just for something different, I'm in! :+1:

**Comment by cheeaun** [comment]
Pixelated stickers folks! :heart_eyes: :space_invader: :coffee: :space_invader: :heart_eyes:

![](https://pbs.twimg.com/media/CadEQ_IUkAEC4vR.jpg)

**Comment by sayanee** [comment]
:clap:

**Comment by renettarenula** [comment]
I neeeed those pixelated stickers! :+1:

**Comment by joerx** [comment]
+1

**Comment by yangzai** [comment]
:+1:

**Comment by aladine** [comment]
+1

**Comment by jurvis** [comment]
+1

**Comment by creativepsyco** [comment]
:+1:

**Comment by gigablah** [comment]
:+1:

**Comment by zz85** [comment]
What's Ekochamber?

**Comment by cheeaun** [comment]
@zz85 can ask @sayanee @notthetup :stuck_out_tongue_closed_eyes:

**Comment by zz85** [comment]
Ohhhhhhhhh.... rings a little bell now!

**Comment by iynaix** [comment]
:+1:

**Comment by teodore** [comment]
+1

**Comment by paradite** [comment]
:+1:

**Comment by llun** [comment]
👍

**Comment by chikathreesix** [comment]
:+1:

**Comment by neeravkumar** [comment]
:+1:

**Comment by cheeaun** [comment]
People, please do note the location of this meetup. It's in **Punggol** area.

---

This information message is brought to you by :coffee: :sunglasses:

**Comment by chardy** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by dvrylc** [comment]
:+1:

**Comment by kwoky** [comment]
:thumbsup:

**Comment by ojimac** [comment]
:+1:

**Comment by cheeaun** [comment]
Everyone (especially new joiners), please be aware that we have a chatroom! Invite yourself via http://kopijs.herokuapp.com/ - great place to hang out and ping others if you got lost during the meetup :stuck_out_tongue:

**Comment by ksaitor** [comment]
Ah! And shameless plug of course:
Feel free to RSVP and comment here too https://meetapp.co/e/224393 !

@cheeaun :stuck_out_tongue_winking_eye:

**Comment by cheeaun** [comment]
@ksaitor :+1:

**Comment by caalberts** [comment]
:+1:

**Comment by alyssaq** [comment]
The date on the homepage says 11 March 😱

**Comment by cheeaun** [comment]
@alyssaq what? different timezone??

**Comment by joerx** [comment]
What's the best way to get there using public transport?

**Comment by cheeaun** [comment]
Everyone (@joerx), if Google Maps is failing you in giving *good* directions, try use [**the super awesome CityMapper**](https://citymapper.com/).

For example, if you stay in Eunos, can try this route: https://citymapper.com/trip/T32dfec

Basically, just go Punggol MRT, and take LRT to Riviera station :+1:

**Comment by ksaitor** [comment]
Holly molly! I've got another meeting at 1pm same day.
@cheeaun Why location is so far away lah?

**Comment by cheeaun** [comment]
@ksaitor it's the ekochamber-special!

**Comment by ardydedase** [comment]
Until what time @cheeaun? Reach 1pm still ok? :)

On Friday, 11 March 2016, Lim Chee Aun <notifications@github.com> wrote:

> @ksaitor <https://github.com/ksaitor> it's the ekochamber-special!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KopiJS/kopi.js/issues/36#issuecomment-195384813>.
>


-- 
Ardy Dedase
webscepter.com

**Comment by cheeaun** [comment]
@ardydedase hmm not really sure, I think still ok, but keep track of updates in the chat room :)

**Comment by cheeaun** [comment]
Everyone, thanks for coming!

This time we didn't take any group photos but never mind! Next time! :smile: 

And the attendees:

- Myself :coffee: :egg: 
- @llun 
- @markfull
- @dvrylc 
- @ojimac
- @kwoky
- @cliener 
- @renettarenula 
- @joerx 
- @yangzai 
- @alyssaq 
- @cbas 
- @chikathreesix
- @paradite 
- @jurvis 
- @jin
- @mgajda
- @eugeneteo
- @dexxtan
- 'su wei', perhaps don't have GitHub account, perhaps @paradite knows?
- another guy (name starts with D) who I confuse the name with @dvrylc
- another one more guy who sits near the other guy above, perhaps @dexxtan knows?
- someone who I don't remember her name :sweat_smile: (with stage freight) probably @sayanee knows?
- roughly two people hanging out with @eugeneteo
- one more guy sitting at @cbas 's table, yes this memory thing is getting very challenging
- anyone else?

Few notes:

- The place is far, but still got people come, don't ask me why. Spacious though service a bit slow and unresponsive sometimes 💁
- Looks like the pixelated #kopijs sticker works :+1: 
- Round table seems like a nice setting though can't fit too many people :sweat_smile: 
- Actually lack of combined tables encourages people to "rotate" seats (well, I did that, not sure about others) :rotating_light: 
- Looks like some of us RSVP without even looking at the location. Will need to further highlight them in next meetup :earth_asia: 
- Some of us went to #ekochamber hosted by @sayanee and @notthetup , which is the whole reason why this meetup is in Punggol :stuck_out_tongue: 

Alright, closing the issue now...

**Comment by sayanee** [comment]
@cheeaun the stage fright girl who wants to speak at meetups is @dandelia 😍 *runs* 😅

**Comment by dexxtan** [comment]
@cheeaun, the two guys sitting around myself and @dvrylc are @iynaix and a guy named Darren. Perhaps xianyi knows his github handle?

**Comment by cheeaun** [comment]
@sayanee @dexxtan thanks!

**Comment by iynaix** [comment]
Darren's github handle is @DtCarrot.

**Comment by cheeaun** [comment]
@iynaix thanks!
