### ISSUE TITLE
Geek Brunch #4 - Saturday, 30 April 2016

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#38]
This month we won't have a #kopijs meetup **BUT** we will have a much bigger **#GeekBrunchSG**!

> A biannual social gathering of all engineers, designers and makers in Singapore!
> 
> Come down and have a brunch.
> Bring someone new, someone curious.
> 
> ❤️ Jointly organised by @webuildsg , @engineersftw and @KopiJS 

Date: **Saturday, 30 April 2016, 11:00AM**
Location: [Wheeler's Yard](http://wheelersyard.com/) ([Foursquare](https://foursquare.com/v/wheelers-yard/525a368f11d236eeeaf8429d)) ([Facebook](https://www.facebook.com/wheelersyard)), [28 Lor Ampas, Singapore 328781
![](http://maps.googleapis.com/maps/api/staticmap?center=Wheeler's+Yard,+28+Lor+Ampas,+Singapore&zoom=15&scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:%7CWheeler's+Yard,+28+Lor+Ampas,+Singapore)](https://www.google.com.sg/maps/place/Wheeler's+Yard/@1.326623,103.8506423,17z/data=!3m1!4b1!4m2!3m1!1s0x31da176278320887:0x8509acc5b21870b3)

##### RSVP

- :+1:-ing this issue, or...
- Go to <https://www.facebook.com/events/883049111807282/> if don't have a GitHub account, or...
- Go to <https://meetapp.co/e/443444/22514> if don't have a Facebook account, or...
- Go to <http://lanyrd.com/2016/kopijs-april/>, or...
- Just go without RSVP-ing, but make sure you ping us the organizers so that you don't get lost or something

#### Organizers

- @sayanee - [Facebook](https://www.facebook.com/sayanee), [Twitter](https://twitter.com/sayanee_), <https://sayan.ee/>
- @miccheng - [Facebook](https://www.facebook.com/miccheng), [Twitter](https://twitter.com/coderkungfu), <http://coderkungfu.com/>
- @cheeaun - [Facebook](https://www.facebook.com/cheeaun), [Twitter](https://twitter.com/cheeaun), <https://cheeaun.com/> - ([I look like this](https://www.flickr.com/gp/cheeaun/g7jWMk))

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @stuti90 @yeouchien @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa @rahulparsani @ishanagr

Those joining, feel free to invite your friends!

**Comment by cheeaun** [comment]
Also inviting @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap @ksaitor @jin @cliener @wizztjh @yinshanyang @hqtan94 @pasindud @yangzai @christabella  @joerx @Learnemy @danishka @timoxley @tjjjwxzq @AlvinderSingh @sevresbabylone @tongrhj @jsstrn @ongmin @staceytay @jurvis @wytanj @shawnlimws @caalberts @dexxtan @paradite @hboon @jianw3i @neeravkumar @chardy @kwoky @ojimac @dandelia @dvrylc @iynaix @DtCarrot and oh gosh who else

**Comment by joerx** [comment]
Too bad. Won't be around this time.

**Comment by cheeaun** [comment]
@joerx 😭

**Comment by kwoky** [comment]
Probably be somewhere in China on that day so will have to give this a miss

**Comment by cheeaun** [comment]
@kwoky :sob:

**Comment by Learnemy** [comment]
+1!
ᐧ

On Sat, Apr 2, 2016 at 2:35 PM, Lim Chee Aun <notifications@github.com>
wrote:

> @kwoky <https://github.com/kwoky> [image: :sob:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/KopiJS/kopi.js/issues/38#issuecomment-204657298>
>



-- 
*Stay curious,*
Elisha Tan

*PS: *Learn how to code with TechLadies: http://www.techladies.co/

**Comment by yangzai** [comment]
+1

**Comment by jin** [comment]
:+1:!!!

**Comment by cheeaun** [comment]
Peeps, don't forget that GitHub now has [**reactions**](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)! 🎉 :smirk:

**Comment by ksaitor** [comment]
:+1:

**Comment by iynaix** [comment]
+1

**Comment by cheeaun** [comment]
Woot! We have a web site! https://geekbrunch.sg/

**Comment by wizztjh** [comment]
If the weather is good, will :bicyclist: along Singapore River to Wheeler yard. Who's joining?

**Comment by llun** [comment]
🚴

**Comment by neeravkumar** [comment]
+1

**Comment by cheeaun** [comment]
Okay, the photos are all up on Facebook: https://www.facebook.com/events/883049111807282/

Since this event is a joint effort and technically a super huge version of Kopi.JS, listing *all* attendees would be near impossible.

Notes (from my observations):

- No one got lost. Some were late. That's good news.
- 100+ (including 2 babies) turned up, according to @miccheng 
- Wheeler's Yard doesn't serve plain water anymore, compared to last year.
- Facebook's weather forecast cannot be 100% trusted.
- For some reason, uploading photos on Facebook event page failed a few times.
- Got one guy got there much earlier than me (and everyone else). I didn't manage to talk to him. My bad.
- Even though our tables are reserved for GBSG, I noticed there are two other tables reserved for something else. Probably another group of people were there, and we messed up their plans.
- Stickers section were not noticeable enough, and probably too messy.
- Babies can actually sleep in noisy environments.

And that's probably it... closing the issue now...
