### ISSUE TITLE
#Milo-Dinosaur meetup - SPH Innov Lab

### ISSUE THREAD

**Issue by kenzoarima** [KopiJS/kopi.js#41]
This is a meetup for folks in Singapore who wanna learn Javascript! We have organised a few learn-together sessions prior, usually over Kopi and Milo. We are currently studying a book written by Jon Duckett titled "**Javascript and jQuery**", and getting coding advice/help from our Kopi.JS masters! Do join us if you wanna learn / improve / teach Javascript! Yay!

Date: **30 Apr 2016**
Location: [**SPH Innovation Lab**](https://medium.com/@stgraphics/bringing-new-technologies-to-newsrooms-through-the-straits-times-innovation-lab-a4891e4f3a76#.1yxs5bwi4)
Address: 1000 Toa Payoh North 318994 [Google Maps](https://goo.gl/maps/Vfb2vuf2mmT2)

<img width="694" src="http://maps.googleapis.com/maps/api/staticmap?center=1.3431592,103.8486961&zoom=16&scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xf26d0b%7Clabel:%7C1.3431592,103.8486961" alt="Google Map of 1.3431592,103.8486961">

***Notes:***
- If you're lost, DM/tweet [@kerion7](https://twitter.com/kerion7), or just comment on this issue!
- RSVP by :+1: -ing this issue, or just come!

**Comment by kenzoarima** [comment]
In view of the rainy weather and generally the partying Friday mood, we will be adjourning tonite's study session! Enjoy your Friday nite! We will update when the next session's date is finalised~

![image](https://cloud.githubusercontent.com/assets/11406216/14734776/54289c2a-089f-11e6-91b4-2d47532548e6.png)

**Comment by kenzoarima** [comment]
Re-opening this issue, pending for a decided date, time and place! Will update when confirmed!

**Comment by kenzoarima** [comment]
Aite~ after a round of confirmation, we have decided to hold it after GeekbrunchSG, on premise! Join us if you wanna study JS!

**Comment by kenzoarima** [comment]
Updated the latest location: SPH Innovation Lab! A number of us will be coming from GeekBrunchSG, so if you are not sure how to get to SPH, just meet us at GeekBrunchSG first!

**Comment by cheeaun** [comment]
For more details on Geek Brunch SG https://geekbrunch.sg/ 👍

**Comment by kenzoarima** [comment]
So despite the rainy and sleepy weather ytd, Milo Dino managed to carry on as planned 💪  
We din really have a journal this week, but we tried out hands on a simple to do app using jQuery!

[Here's our demo](http://codepen.io/kenzoarima/pen/WwaVaw)!

**Comment by kenzoarima** [comment]
oh, and GeekbrunchSG is the awesomezzz! (^.^)_b
