### ISSUE TITLE
KopiJS #23 - Saturday, 28 May

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#44]
Kopi.JS is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Saturday, 28 May 2016, 11AM**
Location: [**The Daily Scoop**](http://thedailyscoop.com.sg/) in **Holland Village** ([Foursquare](https://foursquare.com/v/the-daily-scoop/4bd572c15631c9b61b0ba430))
👉 [43 Jalan Merah Saga, #01-78 Chip Bee Gardens, 278115](https://www.google.com.sg/maps/place/The+Daily+Scoop,+Singapore+278115/@1.3969927,103.8360621,11z/) (near Holland Village MRT, Yellow line)

##### Agenda

Gather there. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) tables. Drink/eat Kopi/whatever. Exchange stickers. Take group selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- I (@cheeaun) [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎

Optional: **RSVP** by :+1:-ing this issue. Or go to https://meetapp.co/e/604466 👍

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
:boom: Inviting @chuyeow @sayanee @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @dqminh @miccheng @stuti90 @yeouchien @cbas @alyssaq @choonkeat @serrynaimo @creativepsyco @ngourlay @mfirdaus @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @hpdang @ardydedase @ahkeno @soareschen @renettarenula @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @duykhoa @rahulparsani @ishanagr

Those joining, feel free to invite your friends!

**Comment by cheeaun** [comment]
Also inviting @leongkui @ruckuus @jmrocela @chernjie @llun @yuhui @nathaniawong @mgajda @fmap @ksaitor @jin @cliener @wizztjh @yinshanyang @hqtan94 @pasindud @yangzai @christabella @joerx @Learnemy @danishka @timoxley @tjjjwxzq @AlvinderSingh @sevresbabylone @tongrhj @jsstrn @ongmin @staceytay @jurvis @wytanj @shawnlimws @caalberts @dexxtan @paradite @hboon @jianw3i @neeravkumar @aladine @iynaix @chardy @kwoky @ojimac @eugeneteo @DtCarrot @dandelia @dvrylc and oh gosh who else

**Comment by yangzai** [comment]
👍

**Comment by miccheng** [comment]
w00t!

**Comment by iynaix** [comment]
+1

**Comment by caalberts** [comment]
have fun!

**Comment by cheeaun** [comment]
@caalberts you not joining? 😭

**Comment by pasindud** [comment]
Sorry Guys I also won't be joining :( Have fun

**Comment by tjjjwxzq** [comment]
:+1:

**Comment by cheeaun** [comment]
@pasindud 😭

**Comment by wizztjh** [comment]
:+1: 

:bicyclist: from tanjung pagar to Daily Scoop via rail way green corridor. DM me if you want to join. https://twitter.com/wizztjh

**Comment by webNinja89** [comment]
(y)

**Comment by ksaitor** [comment]
@cheeaun lacking MeetApp link ;)

**Comment by aralovelace** [comment]
:+1:

**Comment by miccheng** [comment]
Adding @cindylky - get ready for some snail tales over scoops of ice cream fellas! :)

**Comment by footyapps27** [comment]
👍

**Comment by cheeaun** [comment]
Stickers. Much nice. Wow.

![fullsizerender](https://cloud.githubusercontent.com/assets/2296/15471025/60d54a28-2126-11e6-97f7-47c4c98e174a.jpg)

**Comment by llun** [comment]
🚴

**Comment by cheeaun** [comment]
Folk! Obviously The Daily Scoop is not a lunch place but no fear! (cough @cliener cough), we can go to the [Holland Village food court](https://foursquare.com/v/holland-village-market--food-centre/4b925288f964a5201af233e3)!

**Comment by prashantrar** [comment]
RSVP @prashantrar

**Comment by ongmin** [comment]
So we meet at Daily Scoop first then go to to food court later at 12? One
of us stay behind?

**Comment by cheeaun** [comment]
@ongmin hmm, why stay behind?

So for those who might be going there at a later time, make sure to keep track of (location) changes as I'll be posting it **here** (this github issue). I'll also post in the [chatroom](http://kopijs.herokuapp.com/) and on [Twitter](https://twitter.com/kopi_js). Feel free to [tweet/DM me on Twitter](https://twitter.com/cheeaun) or [Messenger me on Facebook](m.me/cheeaun) for more speedier response. 😁

**Comment by cheeaun** [comment]
Hi everyone, we've moved to Coffee Bean!

**Comment by yangzai** [comment]
Eating @ said hawker

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁 

Photos:

- https://www.facebook.com/miccheng/posts/10154261290462229
- (Private) https://www.facebook.com/photo.php?fbid=10153506277966781&set=a.10151948226636781.1073741842.535816780&type=3&theater
- https://theta360.com/s/iZpDcetnkZWvoJYi5u73R9H1w
- https://theta360.com/s/jXZWJ5hWaedeuEqVaQpMOS2q4
- https://theta360.com/s/n60woBBFxYlrfbEsjMBe1Lhh6
- https://theta360.com/s/iapaSrcF7xAlGUgDVERozzNfI
- https://twitter.com/ongmin/status/736464574828810240
- https://twitter.com/yingkh_tweets/status/736557876374736896

And the attendees:

- Myself 😎 
- @laktek 😎 - MAGICAL APPEARANCE
- @yangzai 
- @miccheng (person with 360 deg camera)
- @iynaix (person with new Dell laptop)
- @ongmin 
- @llun 
- @tjjjwxzq 
- @dvrylc
- @engerium (Preshant with the "Pre" instead of "Pra")
- @gigablah (historically expensive Pie t-shirt)
- @creativepsyco (Mohit)
- @zionsg (wear same white shirt as @ongmin ⬜  )
- @Annnnnnnnnnnl (Ann Luo)
- @kenzoarima
- @zellwk
- @giftofjehovah (Jonathan)
- @silverframe (Stefanie)
- @shiado (Melissa)
- @yzdong
- @himynameistimli
- [@meowlivia_](https://twitter.com/meowlivia_) (@oliviale ?)
- @hhandoko
- @SheldonCheng
- [@yingkh_tweets](https://twitter.com/yingkh_tweets) (was with @vivipazos , am I right?)
- @vivipazos
- @Weimankow 
- @GIANTCRAB (Huiren) - *oh come on people, use nicer usernames pls?*
- @dandelia (still deciding whether to buy Macbook Pro or iMac)
- [@jinjin.niu.7](https://www.facebook.com/jinjin.niu.7)
- @chernjie
- @laktek 's friend, who tried to ride on @Weimankow 's unicycle with @chernjie 's assistance ?
- @Annnnnnnnnnnl 's friend who sits near @ongmin and @yangzai ?
- A girl who sits near @Annnnnnnnnnnl , @ongmin, @miccheng and @yangzai ?
- A guy who keeps talking with @gigablah and @laktek ? (also attended the previous SG PHP and JS meetups, gosh I forgot the name)
- A guy from Malacca who were talking with @yzdong, myself, @gigablah and few others? (gosh I forgot the name again)
- A guy who I didn't manage to talk to, but talk to @giftofjehovah, @shiado, @silverframe, @ongming, and few others? He's also one of the first ones to wait in front of The Daily Scoop 🍨 
- anyone else? 😅

Few notes:

- The Daily Scoop suddenly has a private event, so **fortunately** we manage to change place to nearby [Coffee Bean](https://foursquare.com/v/the-coffee-bean--tea-leaf/4b1a2166f964a520b3e723e3) 😢  Next time I'll need to double-confirm the place.
- Toilet in Coffee Bean is kinda weird. Mirrors and doors with no locked/unlocked indicators 🚽 
- Holland Village turns out to be quite accessible for most people, and considered "central" 🤔
- [Sunday Folks](https://foursquare.com/v/sunday-folks/53bd1955498e1369b4c72fc7) looks like a sweet *dating* place tho' it opens at 12 on Saturday 😏 
- The new stickers, for both pixelated KopiJS and Milo Dinosaur turns out to be quite a hit 👾 
- Combined tables might seem like a nice idea to make people feel closer and warmer, but it's difficult for them to get out, if say go toilet or something. Either slide the table out or acrobatically crawl their way out under the table 😅 
- The new title format this time (KopiJS #23) seems to work and less confusing, compared to the previous format (KopiJS 23rd meetup). So, no more confusion whether it's the 23rd meetup or be held on 23rd of the month 😛 
- Nearby food court again proves to be a very convenient nice-to-have, especially for those of us who want more lunch options instead of cafe hipster food.

Closing the issue now...
