### ISSUE TITLE
KopiJS #24 Ramadan-special - Wednesday, 22 June

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#46]
Kopi.JS is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Wednesday, 22 June 2016, 8PM**
Location: **Victory Restaurant** ([Foursquare](https://foursquare.com/v/victory-restaurant-pte-ltd/4dfc9c0e149599f28fcb28b1)),  [701 North Bridge Rd, Singapore 198677](https://www.google.com.sg/maps/place/Victory/@1.3021631,103.8564152,17z/data=!3m1!4b1!4m5!3m4!1s0x31da19b0c530afc9:0x56fdc14ae51c14ab!8m2!3d1.3021631!4d103.8586039?hl=en)

##### Agenda

Gather there. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) tables. Drink/eat Kopi/whatever. Exchange stickers. Take group selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- I (@cheeaun) [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎

Optional: **RSVP** by :+1:-ing this issue.

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by iynaix** [comment]
:+1:

**Comment by caseywatts** [comment]
:+1:

**Comment by prathamesh-sonpatki** [comment]
:+1:

**Comment by DtCarrot** [comment]
:+1:

**Comment by yangzai** [comment]
Exam. Will skip this one.

**Comment by cheeaun** [comment]
@yangzai 😭

**Comment by yangzai** [comment]
@cheeaun I literally will be in an exam hall at that time. lol

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😘

Photos:

- https://twitter.com/nazroll/status/745623632110489600
- https://twitter.com/nazroll/status/745629735158308864
- https://slack-files.com/T024HV01E-F1K5HQ5KM-ac8a99ba70
- https://slack-files.com/T024HV01E-F1K5SJ0CT-3d5485ebeb
- https://slack-files.com/T024HV01E-F1K7J16BU-fcaeb5e3b7
- https://www.facebook.com/photo.php?fbid=10154327236362229&set=a.475431307228.261529.503517228&type=3 (private)

And the attendees:

- Round 1: 
  - Myself 😎 
  - @caseywatts 
  - @JuanitoFatas
  - @iynaix 
  - @DtCarrot (?)
  - @prathamesh-sonpatki 
  - @mongeslani
  - @nazroll
  - two buddies of @nazroll (don't know their GitHub usernames)
  - [@yingkh_tweets](http://twitter.com/yingkh_tweets)
  - [@alvinchangw](https://www.facebook.com/alvinchangw)
  - Ken... Mori? (not sure what's the github/twitter username, perhaps @JuanitoFatas knows?)
  - @vipulnsward
- Round 2:
  - Myself 😎 
  - @coderkungfu
  - @eiwaithein
  - @zionsg
  - @GIANTCRAB
  - @valentine 
  - @caseywatts 
  - @JuanitoFatas

Few notes:

- Most (other) people left after 8PM. The place becomes almost empty. Pretty fast in breaking fast ⚡ 
- Murtabak was good. So good. 😛 
- Most of us join around 7:30 even though I said 8PM. While some join at 8:30. Then another batch at 9PM (second round) 😅 

Closing the issue now...

**Comment by nazroll** [comment]
Win
