### ISSUE TITLE
KopiJS #25 - Saturday, 16 July

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#47]
Kopi.JS is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Saturday, 16 July 2016, 11AM**
Location: [**Drips Bakery Cafe**](http://www.drips.com.sg/) ([Foursquare](https://foursquare.com/v/drips-bakery-cafe/4e6da3468998a706cd8fe080)) ([Facebook](https://www.facebook.com/dripsbakerycafe)) 
👉🗺 [#01-05, 82 Tiong Poh Rd, Singapore 160082](https://www.google.com.sg/maps/place/Drips+Bakery+Caf%C3%A9/@1.2836307,103.8317432,17z/data=!3m1!4b1!4m5!3m4!1s0x31da1970a1fc7359:0xbe31f565f8a599e7!8m2!3d1.2836307!4d103.8339319), near **Tiong Bahru** (green 💚 ) line 🚉 

##### Agenda

Gather there. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) tables. Drink/eat Kopi/whatever. Exchange stickers. Take group selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/). I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue, or http://meetapp.co/e/724447/22514

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by iynaix** [comment]
:+1:

**Comment by cheeaun** [comment]
Note that there's an event, [Singapore Science Festival: Science Buskers Festival](https://www.eventbrite.sg/e/singapore-science-festival-science-buskers-festival-tickets-26193135373) happening on the same day at Vivocity. Possibly can check it out ☺️

**Comment by cheeaun** [comment]
Special invite to *some* of our industry leaders: @sausheong @laurenceputra @chuyeow @choonkeat @kaihendry @coffeesam @winston @jaryl 

Everyone else is welcomed too! 😄

**Comment by choonkeat** [comment]
👍

**Comment by laurenceputra** [comment]
wa, since you tag me alr, I'll try to be there.

**Comment by shujin** [comment]
👍

**Comment by aralovelace** [comment]
:+1:

**Comment by cheeaun** [comment]
Another special invite to *some* of our industry leaders: @subhransu @serrynaimo @mbrochh @uzyn @MugunthKumar @creativepsyco @gigablah @timoxley  👏 👏 👏 

Everyone else is welcomed too! 😄

**Comment by sausheong** [comment]
Like this? 👍

**Comment by cheeaun** [comment]
So there's another event running on the same day too: [I/O Extended 2016](http://www.gdg-sg.org/2016/06/io-extended-2016-sat-jul-16th.html) at NUS 😮

**Comment by uzyn** [comment]
👍

**Comment by creativepsyco** [comment]
I will be busy in I/O Extended that day :(

On Wed, Jul 6, 2016 at 4:24 PM, U-Zyn Chua <notifications@github.com> wrote:

> 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KopiJS/kopi.js/issues/47#issuecomment-230709267>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAhZow5BauJ2L1Ehh_bG7WO1wfgUwLk3ks5qS2YrgaJpZM4JEgRT>
> .
>



-- 
Mohit Singh KANWAL (Mr)

[image: Facebook] <http://facebook.com/mohitkanwal>  [image: Twitter]
<http://twitter.com/mohitkanwal>

**Comment by subhransu** [comment]
Will attend this one folks. 👍

**Comment by winston** [comment]
I should be able to make a brief appearance. :)

**Comment by mbrochh** [comment]
Hmm... yea... that date could work!

**Comment by yangzai** [comment]
👍  (will be leaving early for I/O Extended)

**Comment by miccheng** [comment]
Will try to come!

**Comment by ksaitor** [comment]
cc @romanzolotarev

**Comment by melvinzhang** [comment]
:+1:

**Comment by winston** [comment]
I actually got the date wrong and showed up a week earlier. Luckily @cheeaun was there and we did a pre-kopijs. Haha. I can't turn up tomorrow anymore, so have fun everyone!

**Comment by cheshirecode** [comment]
See you!

**Comment by denisborovikov** [comment]
Thanks for the t-shirt 👕 I'll wear it next time

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos:

- https://www.facebook.com/kopijs/posts/1651385491854737
- some photos by @laurenceputra 

And the attendees:

- Myself 😎 
- @kaihendry + Ruth + 👶 
- @choonkeat + 👧 
- @cliener + 👦 
- @laurenceputra 
- @serrynaimo
- @timoxley
- @iynaix 
- @iynaix 's friend(?) who suddenly joined us
- @shujin 
- @aralovelace 
- @ksaitor 
- @denisborovikov 
- @romanzolotarev 
- @cheshirecode 
- @melvinzhang 
- @yangzai 
- @kenzoarima
- @giftofjehovah
- @silverframe
- @GIANTCRAB
- @markfull
- @geekyme
- [@yingkh_tweets](https://twitter.com/yingkh_tweets)
- [@alvinchangw](https://www.facebook.com/alvinchangw)
- [@candiceaw](https://www.facebook.com/candiceaw)
- A girl who sits on her own when she arrived, was with @giftofjehovah , @silverframe and `yingkh`
- anyone else? 😅 

Few notes:

- The cafe has a nice vibe though most of us split tables, so couldn't manage to talk with everyone 😢 
- Probably a bit not-so-accessible as it's quite a long walk from either Tiong Bahru MRT station or Outram Park MRT station 🚆 
- As for the girl who sits on her own (and look confused), I'll need to find a way to **never* let that happen again 🤔
- Nearby food court, Tiong Bahru market, is useful for (cheap) lunch 🍴

Closing the issue now...
