### ISSUE TITLE
KopiJS #26 - Saturday, 30 July - @audreylim -special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#48]
[Kopi.JS](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Saturday, 30 July 2016, 10AM**
Location: [**Wimbly Lu Chocolates**](http://www.wimblylu.com/) ([Foursquare](https://foursquare.com/v/wimbly-lu-chocolates/4db7be104df0ded98bae8c0c)) ([Facebook](https://www.facebook.com/WimblyLuChocolates)) 
👉🗺 [15-2 Jalan Riang, 358987](https://www.google.com.sg/maps/place/Wimbly+Lu+Chocolates/@1.3473801,103.8676305,15z/data=!4m2!3m1!1s0x0:0x7140ef9ddb0431d4?sa=X&sqi=2&ved=0ahUKEwjeqJ6wqIPOAhWGr48KHUlaBUsQ_BIIggEwDw), near **Serangoon** MRT 🚉 (purple 💜 & yellow 💛  line)

##### Agenda

Gather there. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394) tables. Drink/eat Kopi/whatever. Exchange stickers. Take group selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/) or [join the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by iynaix** [comment]
:+1:

**Comment by miccheng** [comment]
👍

**Comment by cliener** [comment]
👍

**Comment by aralovelace** [comment]
:+1:

**Comment by yangzai** [comment]
👍🏿

**Comment by mariodinatatribalddb** [comment]
👍

**Comment by phamtuanhoang** [comment]
👍

**Comment by mmahinay** [comment]
👍

**Comment by teethmarks** [comment]
hello there! i wish to join the slack team at kopijs.slack.com/messages/milo-dinosaur.
Do I need an invite?

Really new here, so do bear with me! :)

**Comment by cheeaun** [comment]
@teethmarks just put your email here! http://kopijs.herokuapp.com/ 😄

**Comment by teethmarks** [comment]
@cheeaun ahhh ok! teethmarks@gmail.com
Thank you!

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos:

- https://twitter.com/cheeaun/status/759205540920696832
- https://www.facebook.com/cheeaun/posts/10154188028626294
- https://www.facebook.com/miccheng/posts/10154430442962229
- https://www.facebook.com/photo.php?fbid=10154430443667229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/photo.php?fbid=10154430444467229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/photo.php?fbid=10154430472912229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/miccheng/posts/10154430475342229
- https://www.facebook.com/miccheng/posts/10154430490477229
- https://www.facebook.com/miccheng/posts/10154430627772229
- https://www.facebook.com/photo.php?fbid=10154430817677229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/photo.php?fbid=10154430833602229&set=a.475431307228.261529.503517228&type=3

And the attendees:

- Myself 😎 
- @audreylim
- @miccheng 
- Jonathan Oh (@miccheng 's friend?)
- @mmahinay 
- [@yingkh_tweets](https://twitter.com/yingkh_tweets)
- @kaihendry + Ruth + 👶
- @silverframe
- @leokleok
- @SheldonCheng
- @yangzai 
- @iynaix 
- @sayanee 
- @cbas
- @kenzoarima
- anyone else?

Few notes:

- Cafe is nice and cosy but only allows large group table when there's a least 4 person present. 👬 👭 
- Cafe location is quite a walk from MRT station, nearer to bus stops 🚏 
- No nearby cheap-food location 😅 
- @leokleok 's nougat treats are super awesome 😍 
- My sitting position was very good as I can see the door open as people enter the cafe.
- Next time must get cool sunglasses like @cbas and @audreylim 😎 

Alright, closing the issue now...
