### ISSUE TITLE
KopiJS #27 - Sunday, 21 Aug - PHP-special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#49]
[Kopi.JS](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript (or PHP?) is NOT required**.

Date: **Sunday, 21 August 2016, 6PM**
Location: [**Big Street**](https://www.facebook.com/bigstreetsg/) ([Foursquare](https://foursquare.com/v/big-street/56b9d78f498e252acfcb5b86)), [104-106 Jalan Besar, 208828](https://www.google.com.sg/maps/place/Big+Street+Singapore/@1.306302,103.855909,15z/data=!4m5!3m4!1s0x0:0xa316de1b28c53843!8m2!3d1.306302!4d103.855909)

Agenda: Gather. [Chope](http://www.urbandictionary.com/define.php?term=chope&defid=5580394). Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/) or [join the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
This is a preliminary dinner before [PHPConf.Asia](https://2016.phpconf.asia/)!

**Comment by miccheng** [comment]
👍

**Comment by iynaix** [comment]
:+1:

**Comment by yangzai** [comment]
👍

**Comment by yuripertamax** [comment]
👍🏻

**Comment by wartodolin** [comment]
👍

**Comment by erwinsetiawan** [comment]
👍

**Comment by aenglander** [comment]
👍

**Comment by Darsono72** [comment]
I hope can joint.. 😀

**Comment by cheeaun** [comment]
@Darsono72 of course can!

**Comment by brennanneoh** [comment]
👍

**Comment by cheeaun** [comment]
📢  For those coming, feel free to [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/) or [join the chatroom](http://kopijs.herokuapp.com/), if you're lost or something.

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos:

- https://www.instagram.com/p/BJaMn2qhsP29b2nfIMCDPArrhh1tYqu3FviptA0/
- https://twitter.com/PHPConfAsia/status/767326468883910656
- https://twitter.com/kaihendry/status/767307412248199169
- https://www.facebook.com/araphoenix/videos/10154435073402579/ (private)
- https://www.facebook.com/asiahypertextpreprocessors/photos/a.455608854597055.1073741829.429813210509953/655387664619172/?type=3&theater
- https://www.facebook.com/media/set/?set=a.1672660196393933.1073741830.1403249723334983&type=1&l=520ea436e8

And the attendees:

- Myself 😎 
- @miccheng 
- @dshafik
- @alejandromarcu
- @michaelcullum
- @dragoonis + dad
- @dseguy
- @aenglander
- @iynaix 
- @yangzai 
- @brennanneoh 
- @sheshbabu
- @achmadfatoni
- @valentine 
- @kaihendry 
- @aralovelace
- @GIANTCRAB
- @dandelia
- [@yingkh_tweets](https://twitter.com/yingkh_tweets)
- [@alvinchangw](https://www.facebook.com/alvinchangw)
- one guy who arrives together with @valentine (?)
- anyone else?

Few notes:

- The place is **huge**, turns out the 2nd floor could accommodate ~100 people. It's not super accessible, still quite a walk (10-15 mins) from the nearest Rochor MRT station 🚶 🚉 
- Lots of huge tables, can be moved around and combined, very good for big groups. 👭 👬 
- A few hipster food choices but quite expensive. 💸 
- Waiters were kinda noob and slow to respond. One of them doesn't know English 😑
- Some folks got wayyy too early for the event. I'll need to be earlier next time, probably *deceive* them on the timing to be about 30 minutes delayed 😈 
- Thanks @phpconfasia for sponsoring food! 💰 

Alright, closing the issue now...
