### ISSUE TITLE
KopiJS #28 - Saturday, 3 Sept - @miccheng-special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#50]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Saturday, 3 September 2016, 12PM noon**
Location: [**The Bravery**](http://eat.thebravery.sg/) ([Foursquare](https://foursquare.com/v/the-bravery/51f0e03d498ef9340516284b)) ([Facebook](https://www.facebook.com/The-Bravery-Cafe-218682528283255/)), [66 Horne Rd](https://www.google.com.sg/maps/place/The+Bravery+Cafe/@1.3102404,103.861243,15z/data=!4m5!3m4!1s0x0:0x4e4b0a835973393d!8m2!3d1.3102404!4d103.861243)

Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/) or [join the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by huijing** [comment]
U mean 12pm ba.... 🙃

**Comment by cheeaun** [comment]
@huijing 😄 thank you!

So, this #kopijs is a @miccheng -special. It's nearby Hackerspace because the t-shirts are there 😏 

Inviting peeps who are eligible for the t-shirts: @winston @draco @ksaitor @ketsugi @kenzoarima @nazroll 💥 💥

**Comment by valentine** [comment]
Just before WordCamp too! 🎉

**Comment by draco** [comment]
Hello! Thanks for the invitation (and the shirt :P) but I am sorry I can't be there as I won't be in Singapore! I'll join for the next one!

**Comment by robertsky** [comment]
finally, a sane place and time for me. XD

**Comment by ksaitor** [comment]
Thanks for the invite! Unfortunately, I'll be traveling during those dates. Have fun guys. Thanks for the t-shirt! 🙌🏻

**Comment by joerx** [comment]
+1 at last

**Comment by cheeaun** [comment]
Also inviting @sausheong because I need to pass the stickers 😏

**Comment by sausheong** [comment]
Ok thanks! I'll be there!

**Comment by shujin** [comment]
👍

**Comment by winston** [comment]
Sorry. Afraid I can't make it this time because I need to bring my kid to RWS. 😂

**Comment by yangzai** [comment]
can't make it. got class. 12AM can.

**Comment by nattsw** [comment]
Did someone say tshirts

**Comment by aladine** [comment]
This week i will come

**Comment by miccheng** [comment]
:+1:

**Comment by cheeaun** [comment]
Announcement!
===

Everyone! So it seems that Lavender area could be nearby areas with Zika virus cases, so let's take all the necessary precautions and steps with all the mosquito screens, repellents and patches! Better be safe than sorry. If you're concerned about this, feel free to stay at home and miss this event (there's always next time!). 

Here's a visualization of affected areas, via http://viz.sg/viz/dengue/

<img width="387" alt="screen shot 2016-09-02 at 11 57 23 pm" src="https://cloud.githubusercontent.com/assets/2296/18210142/b6cd7994-7169-11e6-92a5-bf72b87c5d61.png">

Thanks!

**Comment by coffeesam** [comment]
👍

**Comment by Weimankow** [comment]
I can't make it :( prepping for sis's wedding next week!!!

**Comment by nattsw** [comment]
I'm a mosquito derepellent so I'll just bunk at home today. Stay clean and alcohol wipes!

**Comment by yangzai** [comment]
:thumbsup: i can go liao

**Comment by yangzai** [comment]
cannot again 😢

**Comment by robertsky** [comment]
I just realised that I have a wedding lunch to attend today. Opps. 有缘无份.

(and I saw @yangzai walking away from HackerspaceSG).

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos:

- https://www.facebook.com/kopijs/photos/?tab=album&album_id=1679649052361714
- https://www.facebook.com/miccheng/posts/10154534623807229
- https://www.facebook.com/photo.php?fbid=10154534754477229&set=a.475431307228.261529.503517228&type=3 (360-deg photo)
- https://www.facebook.com/miccheng/posts/10154534766432229
- https://www.facebook.com/miccheng/posts/10154534801547229
- https://www.facebook.com/miccheng/posts/10154534805082229
- https://www.facebook.com/photo.php?fbid=10154534822057229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/photo.php?fbid=10154534854122229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/photo.php?fbid=10154534885327229&set=a.475431307228.261529.503517228&type=3
- https://www.instagram.com/p/BJ47-bbD0KWiNvO4aRq_tA3r2ELbGuH96ckZ-E0/
- https://www.instagram.com/p/BJ4-IbRjFfR3gMBPmj3ym1wYhdX-rbqYGPqHwI0/
- https://twitter.com/yingkh_tweets/status/772061977711476738
- https://twitter.com/yingkh_tweets/status/772062758179250176

And the attendees:

☕ = those wearing #kopijs t-shirts

- Myself 😎 
- @miccheng 😎 ☕
- [@yingkh_tweets](https://twitter.com/yingkh_tweets)
- @juslee
- @giantcrab
- @aladine 
- @valentine 
- @cbas ☕
- @alyssaq
- @kenzoarima
- @coffeesam 
- @kaihendry 
- @laurenceputra ☕
- @silverframe ☕
- @giftofjehovah
- @sayanee ☕
- @notthetup
- @shujin ☕
- @ongmin ☕
- @SheldonCheng
- @vinamelody (☕ sticker on shirt)
- @ntd251
- @ponyfleisch ☕
- @lnfra (Angeline) + 1
- anyone else?

Few notes:

- The place (Bravery) is surprisingly huge inside as we got two long tables and still got space to accomodate more people 👾 
- Free wifi in Bravery seems to make people happy, somehow 📶 
- Looks like no one is bothered much about Zika virus and stuff, as the cafe inside is air-conditioned and very comfortable (outside super hot!) 🔥 
- Looks like everyone manage to find the place despite me being over-worried about people missing the place since the entrance of the cafe is quite weird 🚪 
- The nice part about this place is *everyone* can see outside from inside as the doors are all glassy 🍷 
- For some, food there is a little expensive so next time I'll need to consider these for next #kopijs location.
- The #kopijs t-shirts turns out a huge hit as I can see people wants them more (for free? 😅 ) and gives a sense of community, or a bunch of people working together in the same company 🏢 💼 
- Unfortunately, the couples don't wear the #kopijs t-shirts together (couple wear), so next time I need to consider this use case as the ROI doesn't work well there 😛 
- Things work out naturally without me doing much, like singing birthday song for @miccheng and suddenly got cake for him (not sure from who?)
- Some attendees felt like have nothing to say or tired, so I'll need to work on this issue somehow, perhaps spark a topic or make them join a group with more talkative people or something 🔈 Or perhaps the group got too big, it creates a sense of tiredness especially for the introverts, so I'll need to experiment making the meetup more introvert-friendly 💭 
- The [Snow](http://www.theverge.com/tldr/2016/7/18/12215312/snow-app-korean-snapchat-clone-filters) app (as recommended by @silverframe ) seems like a pretty cool app to get people around excited (especially when there's nothing to talk about, which serves as a good conversation starter 😏 )
- After the hangout, some of us went for 2nd round at [PourOver Bar](https://foursquare.com/v/ollella-x-the-pourover-bar/56fb5744498e8d157bbda357) which is pretty cosy and small place to hang out 😪 

Alright, closing the issue now...

**Comment by miccheng** [comment]
It came from @ongmin.

**Comment by ponyfleisch** [comment]
what? i was not there. did my evil twin escape again? that bastard..

**Comment by coffeesam** [comment]
var TShirt = new Order({'KopiJS' : 'T-Shirt', 'Qty': 1});

**Comment by coffeesam** [comment]
It's interesting that u conduct retrospective for KopiJS 😆
