### ISSUE TITLE
KopiJS #29 - Sunday, 18 Sept - @jurvis - special

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#51]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Sunday, 18 September 2016, 11AM**
Location: [**I Am Cafe**](http://www.iam.com.sg/) ([Foursquare](https://foursquare.com/v/i-am-cafe/514efe50e4b0fff03729e4e9)) ([Facebook](https://www.facebook.com/Iamathajilane/)), [674 North Bridge Road](https://www.google.com.sg/maps/place/I+am.../@1.3017571,103.8584131,15z/data=!4m5!3m4!1s0x0:0xff7cb4c967fa14d8!8m2!3d1.3017571!4d103.8584131)

Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost, [DM/tweet me](https://twitter.com/cheeaun) or [Messenger me](https://www.messenger.com/t/744426293/) or [join the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by cheeaun** [comment]
So, this #kopijs is a @jurvis -special. Inviting peeps who are *still* eligible for the t-shirts: @winston @draco @ksaitor @ketsugi @kenzoarima @nazroll 💥 💥

**Comment by yangzai** [comment]
A lot of Saturday classes until Nov. 😦

**Comment by lxcid** [comment]
Will try to make it for @jurvis. :)

**Comment by cheeaun** [comment]
Everyone, the date has changed due to @jurvis 's schedule and blame the timezone!

Now it's on Sunday, **NOT** Saturday! Take note!

**Comment by draco** [comment]
Sorry got something on 18, wouldn't be able to make it now :(

**Comment by lxcid** [comment]
Unfortunately, Sunday had family plans already. Sorry guys.

**Comment by miccheng** [comment]
:+1:

**Comment by laurenceputra** [comment]
:+1:

**Comment by llun** [comment]
👍

**Comment by liaujianjie** [comment]
👍 Been a longtime lurker, tomorrow will be my first time!

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos:

- https://www.facebook.com/photo.php?fbid=10154579830607229&set=a.475431307228.261529.503517228&type=3
- https://www.facebook.com/photo.php?fbid=10154579831937229&set=a.475431307228.261529.503517228&type=3

And the attendees:

☕ = those wearing #kopijs t-shirts

- Myself 😎 
- @jurvis 😎 
- @miccheng ☕
- @yangzai ☕
- @laurenceputra 
- @sayanee 
- @Weimankow
- @stanleynguyen
- @ambrosechua
- @chernjie
- @llun 
- @iynaix
- @liaujianjie
- @GIANTCRAB
- @DtCarrot
- @elfgoh
- [@yingkh_tweets](https://twitter.com/yingkh_tweets)
- @cbas and @alyssaq who said hi and bye so fast.
- A girl who came with @elfgoh ?
- two guys speaking with @iynaix and @DtCarrot ?
- anyone else?

Few notes:

- Convenient place but too touristy, food is expensive so not very feasible for students. 💸 
- Not enough seats for everyone unfortunately, since most of us joined late. I probably should have set the time earlier, so that everyone can chope the tables earlier, which is allowed by the restaurant owner, despite that the ordering only starts at 11AM. ⌛ 
- Even though the place has fans and we're sitting "inside", it's still quite hot. Next time I need to survey the humidity of the place too, besides the space availability and busy times. 🔥👾⏰
- Somehow I forgot to distribute the KopiJS stickers this time. 😅
- Next time I shouldn't be *so nice* to the waiter and say chope 6 or 10 seats. I should straight say chope 15 or something? 🤔

Alright, closing the issue now...
