### ISSUE TITLE
KopiJS #30 - Sunday, 16 October

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#52]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Sunday, 16 October 2016, 11:05AM**
Location: **Ya Kun Kaya Toast** ([Foursquare](https://foursquare.com/v/ya-kun-kaya-toast-%E4%BA%9E%E5%9D%A4/4b231bc2f964a520635324e3)), [18 China Street, #01-01, Far East Square](https://www.google.com.sg/maps/place/Ya+Kun+Kaya+Toast/@1.2838988,103.8469524,17z/data=!4m8!1m2!2m1!1sya+kun!3m4!1s0x0:0xfa072ec1345f8321!8m2!3d1.2836327!4d103.8479521)

Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

##### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun) or [ping the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by yangzai** [comment]
👍

**Comment by serrynaimo** [comment]
☕️

**Comment by llun** [comment]
🍭

**Comment by tjjjwxzq** [comment]
:+1:

**Comment by iynaix** [comment]
:+1:

**Comment by laktek** [comment]
👍

**Comment by nathaniawong** [comment]
:+1:

**Comment by draco** [comment]
👍

**Comment by Dillion** [comment]
👍

**Comment by aladine** [comment]
👍

**Comment by lxcid** [comment]
👍

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos:

- https://twitter.com/cheeaun/status/787484709416800256
- https://twitter.com/heliumlife/status/787524921148616704
- https://twitter.com/serrynaimo/status/787571015312297984

🤔 surprisingly no photos of people, if anyone took any photos, please inform me!

And the attendees:

👕  = those wearing #kopijs t-shirts (both coffee and milo dino)

- Myself ☕️ 
- @laktek ☕️ 
- @yangzai 
- @serrynaimo 
- @llun 
- @markfull
- @Dillion 
- @aladine 
- @tjjjwxzq 👕 
- @Drenmi 👕 
- @iynaix 👕 
- @lxcid 
- @cbas 👕 
- @alyssaq
- @davified
- @liuziyi 
- @heliumlife 
- @kenzoarima
- @ardydedase
- @soareschen
- @vivipazos 👕 
- @nathaniawong (late)
- @ksaitor (late)
- [Ka Ho](https://twitter.com/yingkh_tweets)
- [Jacin](https://www.facebook.com/jacinloves)
- [Alvin](https://www.facebook.com/alvinchangw)
- [Adeline](https://www.facebook.com/adeline.setiawan) (?)
- two guys who I forgot the name again 😭 
- one more guy, I think?
- and... one more guy again, talking with @laktek @serrynaimo group?
- anyone... else? 😅 

Few notes:

- Looks like the '11:05 AM' trick doesn't work 😛 
- I purposely don't wear my ☕️  #kopijs t-shirt, just to test the "People don't know I'm the organizer" effect, seems to be working well 😆 
- I forgot to bring my #kopijs stickers because too distracted by giving out the **FREE** t-shirts 👕
- Ya Kun, as always, spacious and lots of tables, even thought the aunties can be a bit *interesting* 💁 
- Interestingly some people still got lost a bit and took some time to find the place 😅 
- Sticker bazaar thing seem to work, though need a huge table for this to happen. Perhaps should standardise this sticker sharing culture in future #kopijs meetups 🤔  (not just Geek Brunch SG)
- After the "brunch", we headed to Hong Lim food complex for lunch. As always, nearby food court is a nice thing to have for #kopijs meetups 🍜 
- Next time I should sit at a more strategic place so that I can walk around easily and not trapped between seats and tables. Being an organizer, I'll need to walk around and make sure people knows what's happening and I need to see what's happening too. 👀 
- The FB hijack event: https://www.facebook.com/events/214425798977223/ , seems like an interesting experiment to see how many new people find out about #kopijs 🤔 

Alright, closing the issue now...
