### ISSUE TITLE
KopiJS #31 - Saturday, 12 November

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#53]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Saturday, 12 November 2016, 10:58AM**
Location: [**A Poke Theory**](http://www.apoketheory.com/) ([Foursquare](https://foursquare.com/v/a-poke-theory/579835b8498e45473060dc13)), [27 Boon Tat Street](https://www.google.com.sg/maps/place/A+Poke+Theory/@1.28122,103.8486135,15z/data=!4m5!3m4!1s0x0:0x29e07f681dfd645e!8m2!3d1.28122!4d103.8486135)

Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.
##### Notes
- No free food. Bring your own money.
- If you're lost or late, please [Message me](https://m.me/cheeaun), [ping the public chat on Messenger](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by iynaix** [comment]
:+1:

**Comment by ongmin** [comment]
:+1:

**Comment by yangzai** [comment]
👎  got class

**Comment by heliumlife** [comment]
👍🏼

**Comment by shujin** [comment]
👍

**Comment by joerx** [comment]
+1

**Comment by mindl** [comment]
👎  Sorry I have a family event that day! I'll join some other time! :) 
- Min

**Comment by mleeburke** [comment]
👍🏻

**Comment by cheeaun** [comment]
Everyone, thanks for coming!! 😁

Photos: not much photos of people, only food photos (Intense conversations prevent photo-taking time 😅 ). If anyone has photos, please ping me!

The attendees:

- Myself ☕️ 😎 
- @a0099654 (Stella) - super early
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- @dandelia ♒️
- @iynaix 
- [Joy Zhang](https://www.facebook.com/joy.zhang.3388)
- [Phang Ling](https://www.facebook.com/ling.phang.1)
- @shujin 
- @stanleynguyen
- @ductoanle (Ethan)
- @SheldonCheng 👕 ☕️ 
- @kenzoarima
- [Alvin](https://www.facebook.com/alvinchangw) 👛 
- @silverframe
- @adityamenon
- @himynameistimli
- @leokleok
- @ongmin - super late
- anyone else?

Few notes:

- Nice place with very convenient location (CBD). The food, known as [Poke]()https://en.wikipedia.org/wiki/Poke_(fish_salad), is a bit expensive but really, really tasty (and feels healthy). No coffee this time, but got hipster tea and interesting smoothies. 😋 
- It rained around 11:15AM but didn't stop people from joining. 🌧 
- I was initially planning to sit at the 6-seat tables, but seems like the chairs are too high and uncomfortable. We end up sitting on the 4-seat tables but shift the other tables to form a longer table. Luckily the owners didn't bother much even though I get weird stares from them sometimes 👀 
- "10:58AM" seems to work quite well... @a0099654 (Stella) misread it as "10:40" or something and came earlier than me 😅  Turns out that 5/6 of us reached the place **BEFORE** 11:00AM, which is *very* rare 😆 
- I purposely don't wear my ☕️ #kopijs t-shirt again. Seems like no effect this time. However only **one** person, @SheldonCheng wears the #kopijs shirt among all the attendees 👕 🤔 
- #kopijs stickers stock running out but should be able to last until end of this year, including the next meetup #54 . The [magnets](https://twitter.com/cheeaun/status/777531446302871553) are pretty cool but doesn't seem to excite much, except myself 👾 
- This time, my seating is much better but the overall distribution of attendees' seatings are a bit *off*. Also I'll need to make it clear that this meetup is not about me and everyone talking *only* to me. I'll need to encourage more many-to-many conversations instead of one-to-many or one-to-one, so that the quiet/introvert ones feel more involved instead of being left out. 👬👭👬👭👬👭👬👭
- Turns out there's washroom in the cafe even though the door at the back is labeled as 'Staff'. 🚽 

Alright, closing the issue now... 👋
