### ISSUE TITLE
KopiJS #32 - Sunday, 27 November - DevFest.Asia edition

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#54]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

Date: **Sunday, 27 November 2016, 11:00AM**
Location: [**ArtScience Museum**](http://www.marinabaysands.com/museum.html) ([Foursquare](https://foursquare.com/artscimuseum)), [10 Bayfront Ave, Rainbow Room, Basement](https://www.google.com/maps/place/ArtScience+Museum/@1.2862792,103.8570776,17z/data=!3m1!4b1!4m5!3m4!1s0x31da19042950679d:0x81c847e129eec549!8m2!3d1.2862738!4d103.8592663)

Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.
##### Notes
- No free food. Bring your own money.
- If you're lost or late, please [Message me](https://m.me/cheeaun), [ping the public chat on Messenger](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- I [look like this](https://www.flickr.com/gp/cheeaun/g7jWMk) 😎
- The owner of the place is not aware of the meetup so don't ask him/her about it.

Optional: **RSVP** by :+1:-ing this issue or [here](http://www.eventnook.com/event/devfestasiaevents2016/home).

If you don't have a GitHub account, no worries, still join us! :kissing_heart:

**Comment by iynaix** [comment]
:+1:

**Comment by yangzai** [comment]
👍  exam over

**Comment by aladine** [comment]
👍

**Comment by notthetup** [comment]
But but but... WebAudio Hack Day!! https://www.meetup.com/Singapore-MusicTech-Meetup/events/235097215/

**Comment by stanleynguyen** [comment]
👍

**Comment by miccheng** [comment]
@ylla

**Comment by miccheng** [comment]
:+1:

**Comment by Jonalogy** [comment]
:thumbsup:

**Comment by ardydedase** [comment]
👍

**Comment by tjjjwxzq** [comment]
:+1:

**Comment by dexxtan** [comment]
:+1:

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

Photos:

- https://www.facebook.com/devfestasia/photos/a.644086022386966.1073741828.640604666068435/937580266370872/?type=3&permPage=1
- https://www.facebook.com/pg/kopijs/photos/?tab=album&album_id=1733068433686442
- Anyone else took photos? 😃 

Attendees:

- Myself ☕️ 
- @sxywu
- @iynaix 
- @tjjjwxzq
- @Drenmi
- @yangzai 
- @aladine 
- @stanleynguyen 
- @miccheng 
- @SheldonCheng
- @kenzoarima
- @oliviale
- @zyml
- @zhuohongwei
- @kahwee
- @sebdeckers
- @alyssaq
- @ipekt
- @Chi-Loong
- @kennethormandy
- @ajmalafif
- @serrynaimo
- [Adeline](https://www.facebook.com/adeline.setiawan)
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- [Lisa Kwok](https://www.facebook.com/lisa.kwok.7) + 1
- 2 guys I forgot the name from 123RF
- ... and a few more guys/girls who I totally forgot. Sorry!! 😅 

**Please ping me or this issue if you're left out in the list above. THANKS!**

Few notes:

- There were some confusion in the beginning as the place (initially Rainbow Room at the basement of ArtScience Museum) was not set up and doesn't really have coffee (or any drinks/food at all). We moved to FabCafe instead as it's easier for people for find (on the ground floor near entrance) 🚪 
- For some reason, there were a few uncles joining the hangout, not sure how or why they join but they left immediately after telling them the "agenda" of the meetup 😅 
- FabCafe is a very nice place, but having a large group proves to be difficult as the other tables were swiftly *choped* by (mostly) tourists (and kids) 👨‍👩‍👧‍👦 Some of us even sit of the kids' tables and chairs 💺 The table and seating setup also makes it difficult to walk around 🚶
- Thanks @serrynaimo for the *cough* promo code *cough* ☕️ 
- The meetup ended around 1PM as the speakers including myself have to join the NASA exhibition in ArtScience Museum.
- I forgot to give out stickers as I was too busy talking and also forgot to eat my croissant 😱 
- Wearing the #kopijs shirt proves to be useful as people can immediately recognize me as the organizer, though it kind of grabs too much attention 👀 

Alright, closing the issue now...
