### ISSUE TITLE
KopiJS #33 - Sunday, 11 December

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#55]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Sunday, 11 December 2016, 10:57AM**
🗺  Location: [**The Betterfield**](https://thebetterfield.com/) ([Foursquare](https://foursquare.com/v/the-betterfield/54faa055498e665a4fec2d4b)), [#01-03, 100 High Street](https://www.google.com.sg/maps/place/The+Betterfield/@1.290632,103.849984,15z/data=!4m5!3m4!1s0x0:0xacffffa81e89df33!8m2!3d1.290632!4d103.849984)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun), [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSPV is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :kissing_heart:

**Comment by yangzai** [comment]
👍

**Comment by heliumlife** [comment]
+1

**Comment by lisatjide** [comment]
👍👍👍

**Comment by minghaoteoh** [comment]
wha. auspicious time!

**Comment by shujin** [comment]
👍

**Comment by rubyvictor** [comment]
👍🏻👍🏻👍🏻👍🏻

**Comment by tjjjwxzq** [comment]
:+1:

**Comment by miccheng** [comment]
👍

**Comment by sebdeckers** [comment]
Does this place serve kopi? https://thebetterfield.com/menu

**Comment by kaihendry** [comment]
Betterfield is closed! We are going to the Adelphi basement (where Jaben headphone store is)

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://www.facebook.com/miccheng/posts/10154847739507229
- https://www.facebook.com/media/set/?set=a.1741304352862850.1073741833.1403249723334983&type=1&l=cd549e9e2b
- And few more photos by @kaihendry if he has the time to upload them.

### 👨‍👩‍👧‍👦 Attendees

- Myself 😎 
- @kaihendry + 1 + 👶 
- @yangzai 
- @heliumlife 
- @kahwee
- @kahwee 's friend (I forgot name 😅 )
- @lisatjide 
- @minghaoteoh 
- @shujin 
- @adityamenon
- @tjjjwxzq 👕 
- @Annnnnnnnnnnl
- @miccheng
- @silverframe
- @kenzoarima
- @SheldonCheng
- @choonkeat
- [Joy Zhang](https://www.facebook.com/joy.zhang.3388)
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- Anyone else?

### 🗒 Notes

- So the place (Betterfield) was closed for the weekend because they have a staff outing. Quite [unexpected](https://www.facebook.com/Annnnnl/posts/765428266937607) but luckily everyone helped in finding another nearby place (Thanks a lot! 😭) and we end up at the [Auntie Teo Place](https://foursquare.com/v/auntie-teo-place/4ba1b491f964a520d5c837e3), basement of The Adelphi building 🏢
- Turns out the place is pretty nice. Lots of tables and chairs to chope. Legit kopi/teh (tarik) and cheap ([comfort](https://www.instagram.com/p/BN4CHY1AM7F)) food 😋 
- Thanks to @miccheng for posting on Facebook and @kaihendry on GitHub issue here about the location change. I posted the location change in all over the internetz and socialz media, didn't get any messages from anyone being lost, so hopefully nothing bad happen 😅 We also wrote a message on a piece of paper and @kahwee slide it at the "welcome carpet" in front of the BetterField cafe entrance 😅
- This time I remember to give out stickers, though I forgot to give the magnets (*cough* limited edition *cough*) 👾 
- Despite the location change "tragedy", everything seems chill after that as we split into two long tables. The table setup also makes it easy for me and others to move around and talk with others 🍴 
- Looks like my "10:57AM" trick didn't work this time. Will experiment more next time 😜

Alright, closing the issue now... 👋
