### ISSUE TITLE
Geek Brunch #5 - Saturday, 11 February 2017

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#56]
This January we won't have a #kopijs meetup BUT we will have a much bigger #GeekBrunchSG on February!

> A biannual social gathering of all engineers, designers and makers in Singapore!
> 
> Come down and have a brunch.
> Bring someone new, someone curious.
> 
> ❤️ Jointly organised by @webuildsg , @engineersftw and @KopiJS 

Website: https://geekbrunch.sg/
Date: **Saturday, 11 February 2017, 11:00AM**
Location: [**Wheeler's Yard**](http://wheelersyard.com/) ([Foursquare](https://foursquare.com/v/wheelers-yard/525a368f11d236eeeaf8429d)) ([Facebook](https://www.facebook.com/wheelersyard)), [28 Lor Ampas, Singapore 328781
![](http://maps.googleapis.com/maps/api/staticmap?center=Wheeler's+Yard,+28+Lor+Ampas,+Singapore&zoom=15&scale=2&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:%7CWheeler's+Yard,+28+Lor+Ampas,+Singapore)](https://www.google.com.sg/maps/place/Wheeler's+Yard/@1.326623,103.8506423,17z/data=!3m1!4b1!4m2!3m1!1s0x31da176278320887:0x8509acc5b21870b3)

##### RSVP

- :+1:-ing this issue, or...
- Go to https://www.facebook.com/events/663549580471268/ if don't have a GitHub account, or...
- Just go without RSVP-ing, but make sure you ping us the organizers so that you don't get lost or something

#### Organizers

- @sayanee - [Facebook](https://www.facebook.com/sayanee), [Twitter](https://twitter.com/sayanee_), https://sayan.ee/
- @miccheng - [Facebook](https://www.facebook.com/miccheng), [Twitter](https://twitter.com/coderkungfu), http://coderkungfu.com/
- @cheeaun - [Facebook](https://www.facebook.com/cheeaun), [Twitter](https://twitter.com/cheeaun), https://cheeaun.com/

**Comment by cheeaun** [comment]
Testing 👋

**Comment by yangzai** [comment]
👋 🇨🇭 👎

**Comment by cheeaun** [comment]
A little late to close this but oh well...

### 📷 Photos & videos

- https://www.facebook.com/photo.php?fbid=10154879727405928&set=gm.689039364588956&type=3&theater
- https://www.facebook.com/cheeaun/media_set?set=a.10154923800801294.1073741833.744426293&type=3
- https://www.youtube.com/watch?v=0unaeYJETR4
- and more... https://www.facebook.com/events/663549580471268/?active_tab=discussion

### 👨‍👩‍👧‍👦 Attendees

> Since this event is a joint effort and technically a super huge version of Kopi.JS, listing all attendees would be near impossible.

### 🗒 Notes (from my observations)

- No one got lost (I hope). Some were late but that's fine 🗺 
- Roughly 100 people attended? 🤝 
- Wheeler's Yard became better, more responsive, even put a 'Private event' sign so that it would not be confusing. Next time we probably need a huge 'Geek Brunch' flag/signboard to tell people this "private" event is the *right one* 🎉 
- Weather forecast seems okay, didn't rain, I think? 🌧 
- Stickers section is still not noticeable enough. The table is too overcrowded for people to notice it. There were also too many stickers, some even fall off the table 👾 
- Announcements during group photo didn't work out well. Voice too low, surroundings too noisy, no one's paying attention because waiting for the photo to be taken. 📸 
- We announced The Geek Path https://thegeekpath.com/ and FOSSASIA http://fossasia.org/
- Eventhough the space in Wheeler's Yard is huge, but walking areas were pretty tight so it's not easy to walk around, even for the waiters/waitresses. Probably next time really need a better place 🚶
- Nothing of value was lost, I hope. I've double-checked. 🕵️ 

That's all. Closing the issue...
