### ISSUE TITLE
KopiJS #34 - Sunday, 5 March

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#57]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Sunday, 5 March 2017, 10:59AM** ([Add to Google Calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=cTgycGIzZXVmamNsamYxNG1oMjRxdmwwY2MgZG5odW51NDJmb3RtZWZvdXVzZzRqOGlwMGtAZw&tmsrc=dnhunu42fotmefouusg4j8ip0k@group.calendar.google.com&catt=false&pprop=HowCreated:DUPLICATE&hl=en-GB&scp=ONE))
🗺  Location: [**Coffee & Toast**](http://www.coffeeandtoast.com.sg/) ([Foursquare](https://foursquare.com/v/coffee--toast/4f42290de4b0e5bc142e3c94)), [#01-93/94, 9 Raffles Boulevard, Millenia Walk](https://www.google.com.sg/maps/place/Coffee+%26+Toast/@1.2937073,103.8599077,15z/data=!4m5!3m4!1s0x0:0x232d67a76c36741!8m2!3d1.2937073!4d103.8599077)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun), [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSPV is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :kissing_heart:

**Comment by jin** [comment]
☕️ ☕️ ☕️ ☕️ ☕️ ☕️ ☕️

**Comment by yangzai** [comment]
❤️ ☕️ 🇨🇭 🚫 👎

**Comment by jsstrn** [comment]
@jin are you back in Singapore?

**Comment by jin** [comment]
@jsstrn yes!

**Comment by llun** [comment]
🤔

**Comment by cheeaun** [comment]
Testing https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=cTgycGIzZXVmamNsamYxNG1oMjRxdmwwY2MgZG5odW51NDJmb3RtZWZvdXVzZzRqOGlwMGtAZw&tmsrc=dnhunu42fotmefouusg4j8ip0k@group.calendar.google.com

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos/Videos

- https://www.facebook.com/pg/kopijs/photos/?tab=album&album_id=1790840797909205
- https://www.flickr.com/photos/cheeaun/albums/72157680957812456
- Live stream: https://www.youtube.com/watch?v=Kvp5bjH6Cjo

### 👨‍👩‍👧‍👦 Attendees

- Myself 😎 
- @kaihendry + 1 + 👶 
- @jin 
- @burnflare
- @anonoz
- @shujin
- @malleus
- @olefirenko
- @sebdeckers
- @silverframe
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- 2 guys and 2 girls who I don't quite remember the name 😅 
- Anyone else?

### 🗒 Notes

- The place is quite empty and spacious. A bit hard to find for some as it's part of Millenia Walk but outside of the building. A bit easy because it's just outside of Exit B of Promenade MRT station. 🚉 
- Only breakfast/light food, got lunch food but not many choices. 🥘 
- There's no toilet in the "restaurant", have to walk all the way out into the mall 🚽 
- Lots of small tables that can be joined, quite flexible, but still have to split into two "sections". ✌️ 
- Perhaps due to the 2-month hiatus or late announcements (just 1 week) or lack of marketing, there's less people, mainly less regulars but somehow got more new people 🤔 
- No wifi there for me to steal which makes it hard for me to do the live-streaming. 📹 
- I tried my [360-degree live-streaming](https://www.youtube.com/watch?v=Kvp5bjH6Cjo) and it looks very blurry probably due to the settings or the slow Internet(?) 📹 
- As always, I got stuck at the corner of the table (trapped), because most people just don't want to sit at the corner and I can't really tell people around to sit there. 💺 
- Looks like my "10:59AM" trick works just a bit, so I'll tweak it more next time 😛 

Alright, closing the issue now... 👋
