### ISSUE TITLE
KopiJS #35 - Sunday, 2nd April

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#58]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Sunday, 2 April 2017, 10:57AM**
🗺  Location: [**The Betterfield**](https://thebetterfield.com/) ([Foursquare](https://foursquare.com/v/the-betterfield/54faa055498e665a4fec2d4b)), [#01-03, 100 High Street](https://www.google.com.sg/maps/place/The+Betterfield/@1.290632,103.849984,15z/data=!4m5!3m4!1s0x0:0xacffffa81e89df33!8m2!3d1.290632!4d103.849984)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun), [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSPV is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :kissing_heart:

**Comment by cheeaun** [comment]
Inviting @jurvis because might already be in SG?

**Comment by jurvis** [comment]
@cheeaun I am back indeed! I'll check with my family if they have any plans for me that day and RSVP soon :smile:

**Comment by miccheng** [comment]
@cheeaun LOL... make sure its open this time. :)

**Comment by cheeaun** [comment]
Choped: http://cho.pe/gRJH4 👍

**Comment by joerx** [comment]
+1

**Comment by cheeaun** [comment]
Woot, tomorrow!

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://web.facebook.com/pg/kopijs/photos/?tab=album&album_id=1807579202902031
- https://www.flickr.com/photos/cheeaun/albums/72157678826267233

### 👨‍👩‍👧‍👦 Attendees

- Myself 😎
- @miccheng 
- @joerx + 1 (?)
- @jin 
- @ardydedase
- @kenzoarima
- @sebdeckers 
- @alyssaq
- @gylim78
- @pasindud (?)
- @iynaix 👕
- [Alvin](https://web.facebook.com/alvinchangw)
- [Ka Ho](https://web.facebook.com/einfinity.evoxenon)
- Anyone else?

### 🗒 Notes

- The place is very empty and spacious. The staff were pretty chill (slow) to even open the place at 11AM. Lots of tables and chairs, still got so much space to walk around.
- Accessible (walkable) from either City Hall or Clarke Quay MRT stations. Few bus stops around too.
- I didn't do any 360-deg photos/videos and distribute the stickers this time. Mainly familiar faces.
- This time, I choped 15 seats via [Chope](http://www.chope.co/) but looks like no need actually.
- Looks like the `10:57AM` trick didn't work this time. Perhaps everyone already knows that they can be late 😅  Or perhaps it's lazy Sunday 😅 

Alright, closing the issue now... 👋

**Comment by zionsg** [comment]
Last minute attendee at 1330hrs:
- @zionsg
