### ISSUE TITLE
KopiGo #36 - Saturday, 27th May

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#59]
## [<img src="https://2017.gophercon.sg/img/gopherconsg.svg" align="right" width="150" alt="">](https://2017.gophercon.sg/)📢  README FIRST! 📢 

This is a **super special edition** made for the [GopherCon Singapore](https://2017.gophercon.sg/) peeps! Actual name for this meetup is "KopiJS" but don't be confused, this meetup has never been about JS and the name is made up for fun (It's a trap!). Go peeps are welcomed! Non-Go peeps are welcomed too!

Okay now back to our regularly schedule program...

---

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 27 May 2017, 10:57AM**
🗺  Location: [**the.twenty.cavan**](https://www.facebook.com/the.twenty.cavan/) ([Foursquare](https://foursquare.com/v/thetwentycavan/57c2888e498eaf432775ef8d)), [20 Cavan Road](https://goo.gl/maps/nKQdhDWx6sS2) ([Street View](https://goo.gl/maps/pwfaqgG2K7t))
⚡️ Bonus: [**Hackerspace SG**](https://hackerspace.sg/) is [very nearby](https://hackerspace.sg/location/), so can check it out after brunch!

<a href='https://citymapper.com/go/xk2hqe' target="_blank"><img src="https://static.citymapper.com/img/embed/GetMeThere_Citymapper.png" alt="Get directions with Citymapper" /></a>

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun), [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSPV is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :kissing_heart:

**Comment by valentine** [comment]
👍

**Comment by miccheng** [comment]
I have to GO! 👍

**Comment by aladine** [comment]
Let's GO 👍

**Comment by jin** [comment]
👍

**Comment by llun** [comment]
🤔

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://www.facebook.com/miccheng/posts/10155372459072229 (private) by @miccheng 
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- Myself 🤒 
- @miccheng 👕 
- @jin 
- @llun 
- @laktek 👕  + 1
- @aladine 
- @kenzoarima (for few minutes only)
- @sebdeckers
- @alyssaq
- @iynaix
- @jeanwei (?)
- @audreylim
- @tatatee
- @hyperair
- @choonkeat + 👦 
- @ChimeraCoder
- @davecheney
- [Luther](https://www.facebook.com/lufeng)
- [Alvin](https://www.facebook.com/alvinchangw)
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- ...and 7/8 more people who I don't remember, perhaps @audreylim can help here 😅 
- Anyone else?

### 🗒 Notes

- The place is very empty and spacious. Lots of tables and chairs. The owner/staff were very helpful in accommodating more seats despite me booking 10 to 12 seats via Chope 💺 
- The place is a little hard to find and easily missed. Plus points would be nearby Lavendar MRT and also Hackerspace for after-brunch activities 🕵️ 
- I didn't do any 360-deg photos/videos but distributed the stickers though doesn't seem to have much demand anymore 🤔  Probably need to design new ones 🤔 
- Looks like the 10:57 AM works (too well) for uh, mostly, non-locals 😏  The rest came in at around 11:30 to 12 😅 
- Food and drinks were decently priced though one person (not sure who) forgot to pay, which I paid at the end (one smoothie) 🍹 

Alright, closing the issue now... 👋

**Comment by miccheng** [comment]
Made my post public.
