### ISSUE TITLE
Kopi.rb #37 - Saturday, 24th June

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#60]
## [<img src="http://www.reddotrubyconf.com/assets/rdrc2017_logo_576-0e50e5fd0c6f296b98bc9ad125e4180bb789f73541954421bcbded6466ede41d.png" align="right" width="150" alt="">](http://www.reddotrubyconf.com/)📢  README FIRST! 📢 

This is a **super special edition** made for the [RedDotRubyConf](http://www.reddotrubyconf.com/) peeps! Actual name for this meetup is "KopiJS" but don't be confused, this meetup has never been about JS and the name is made up for fun (It's a trap!). Ruby peeps are welcomed! Non-Ruby peeps are welcomed too!

Okay now back to our regularly schedule program...

---

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 24 June 2017, 10:30AM**
🗺  Location: **[Mr Teh Tarik Express](https://foursquare.com/v/mr-teh-tarik-express/4b4feb11f964a520801927e3)** ([Facebook](https://www.facebook.com/pages/Mr-Teh-Tarik-Express-at-Far-East-Square/438257076304524)), [135 Amoy Street, #01-01, Far East Square](https://goo.gl/maps/W6ezmuC4z6B2)

[<img width="320" alt="photo of the place" src="https://igx.4sqi.net/img/general/width960/80070973_z16kecVZ6kAUZB-D5Tu7EON7bW3C3nngwsZt8oXL5lw.jpg">](https://foursquare.com/v/mr-teh-tarik-express/4b4feb11f964a520801927e3/photos) [<img width="320" alt="360 photo of the place" src="https://user-images.githubusercontent.com/2296/27252579-939f06fa-5394-11e7-9379-e3f44ff8e3a0.png">](https://goo.gl/maps/wLZwbTCNCWE2)

<a href='https://citymapper.com/go/kpranh' target="_blank"><img src="https://static.citymapper.com/img/embed/GetMeThere_Citymapper.png" alt="Get directions with Citymapper" /></a>

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun), [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSPV is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :kissing_heart:

**Comment by jin** [comment]
👍

**Comment by yogendra** [comment]
👍👍👍

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://www.facebook.com/pg/kopijs/photos/?tab=album&album_id=1857636701229614
- https://www.flickr.com/photos/cheeaun/albums/72157685442412835
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- Myself 🤔 
- @jin 
- @dtcarrot
- @drenmi 
- @kenzoarima
- @iynaix 👕
- @giantcrab
- @SheldonCheng
- @dtinth
- @Learnemy (last minute)
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- One more guy, I didn't get his name. Anyone?
- Anyone else?

### 🗒 Notes

- Lots of seats. Mostly drinks, got very few food choices. The place got deleted by someone on Google Maps, and some people got redirected to the *other* Mr Teh Tarik place. 😅 
- The place is pretty hard to find as there seems to be *two* Amoy St and Google maps got confused. Not sure if anyone got lost, but seems like communication channels are not working despite it being mentioned on this issue. Looks like I need to further raise this up to encourage better communication 📞 🗺 
- Distributed a few stickers this time. No 360 photos/videos.  👾 
- Looks like 10:30AM is probably too early. Perhaps everyone got too drunk from the RedDotRubyConf afterparty. Probably Kopi.rb is a weird name and not compelling enough for people to join 🤔 Will need to rethink some strategies for new people to know more about this kind of no-agenda meetups. 🤔 
- After the meetup, most of us went for lunch. Went to a pretty cool new hipster place called "ETL quantum food lab". Kinda expensive but hopefully everyone is satisfied 😌 

Alright, closing the issue now... 👋

**Comment by kenzoarima** [comment]
Michael, mostly based in Philippines, here for Ruby Conf. Pretty cool guy having a deep philosophical talk with @Drenmi ... but didn't get this github handle... :sweat_smile:

**Comment by cheeaun** [comment]
@kenzoarima ah ok, then could be @rykov

**Comment by kenzoarima** [comment]
That gemfury website of his... most likely ;)

**Comment by rykov** [comment]
Hey all.  Sorry it took a while to respond, but yes, that was me.  Thank you all for hosting me, for the kopi, and the deep philosophical talk.  Also, thanks @kenzoarima for plugging :fire:[Gemfury](https://gemfury.com) - I can retain some shame 🤣 

Just wanted to follow up on the side-project discussion, and my promise to post when my "Jekyll for email newsletters" project is ready to launch.  Here's the [repo](https://github.com/rykov/paperboy) and the [site](https://www.paperboy.email/).  I'm planning to release v0.1 build early next week, and promote it around all the usual spots.  Please let me know what you think, alternative name ideas, features, etc.  And last but not least, **please hit "⭐️ Star"** if you think it's a good idea and want to promote its future development and use.

Thanks again! I hope to see you all again at the next conference or on my next visit to SG.
