### ISSUE TITLE
KopiJS #40 - Saturday, 6th January 2018

### ISSUE THREAD

**Issue by cheeaun** [KopiJS/kopi.js#63]
[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**

🗓  Date: **Saturday, 6 January 2018, 11:00AM**
🗺  Location: [The Bravery](http://thebraverycafe.com/), [66 Horne Road, Singapore](https://goo.gl/maps/QrqQDUCh1U52)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](https://slackpass.io/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by burnflare** [comment]
I’ll be there!

**Comment by cheeaun** [comment]
Combo event! https://www.facebook.com/events/127750754683118/

**Comment by lxcid** [comment]
Will try to join 👍

**Comment by miccheng** [comment]
👍

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://www.facebook.com/miccheng/posts/10156004906372229
- https://www.facebook.com/groups/creativecrewsg/permalink/10155758098905202/
- https://twitter.com/yingkh_tweets/status/949474334791294977
- Any other photos?

🗒 Notes

- Bravery cafe is a nice spot, as tried before. Tables are huge and lots of seats. I choped 10:30AM but staff said I chope 1PM, oh well.
- I was late for 3 minutes but turns out fine.
- Combo meetup with Creative Crew's FB [event page](https://www.facebook.com/events/127750754683118/) seems fine. 43 interested, 15 went, 82 invited. Some seems still confused on how an "informal meetup" works.
- Got some nice chocolates from @audreylim . Thanks!
- Tried to listen to @webuildsg LIVE podcast but too noisy (the cafe's walls don't seem to absorb sound well).

Alright, closing the issue now...

PS. This is probably the last time I initiate a Kopi.JS meetup, next few hangouts will be completely initiated by my co-organizers (if you want to help co-organize, please contact me @cheeaun ).
