### ISSUE TITLE
KopiJS #46 - Saturday, 13 October 2018

### ISSUE THREAD

**Issue by kenzoarima** [KopiJS/kopi.js#70]
![yakun-github](https://user-images.githubusercontent.com/11406216/46709394-25f7bc80-cc76-11e8-807f-c77b7e35e978.jpg)

It's time to enjoy our aromatic asian coffee again at Yakun! The regular toasted and steamed bread for our sumptuous brunch!

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 13 October 2018, 10:57AM**
🗺  Location: **Ya Kun Kaya Toast** ([Foursquare](https://foursquare.com/v/ya-kun-kaya-toast-%E4%BA%9E%E5%9D%A4/4b231bc2f964a520635324e3)), [18 China Street, #01-01, Far East Square](https://www.google.com.sg/maps/place/Ya+Kun+Kaya+Toast/@1.2838988,103.8469524,17z/data=!4m8!1m2!2m1!1sya+kun!3m4!1s0x0:0xfa072ec1345f8321!8m2!3d1.2836327!4d103.8479521)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by kenzoarima** [comment]
cc @davinaleong . Join us if you are free~

**Comment by lxcid** [comment]
Awesome! Will be there. See you guys!

**Comment by kenzoarima** [comment]
Thanks everyone for coming! 😄 

### 📷 Photos

- https://twitter.com/kopi_js/status/1050957117287362560
- https://twitter.com/kopi_js/status/1050977749957992448
- https://twitter.com/qiannyqianhere/status/1050974439117021184
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- @kenzoarima 😎
- @cheeaun 😎
- @iynaix
- @shiling
- @PicoCreator
- @helplah
- @yadunut
- @ravernkoh
- @dexterleng
- @zionsg
- @LoneRifle
- @qiannyqian
- @sophieyang0813
- @DtCarrot
- @lxcid
- @swxsw
- Su Wei
- @yingkh
- Anyone else?

### 🗒 Notes

- A heartful ❤️ thanks to everyone who came in spite of the sudden tropical shower 🌧, and enjoyed their coffee fix and kaya toast 🍯🍞!
- Good thing we managed to colonise the tables indoors (the round tables in the middle aisle) and everyone could manoeuvre across tables to chat!
- Sophie could finally put a face to the github person 👾 whom she has been interacting for the past few months!
- Nice to see more new people attending kopijs and sharing their thoughts and learnings with the community! Together we have fun and thrive 💪!
- Yakun could really consider supporting e-payments (e.g. PayLah!, NETs) to catch up with the #cashless trend, so that we could spend and eat more food without worrying about not having enough cash 💵.
- Many thanks again for coming to #kopijs!

**Comment by yingkh** [comment]
With regard to the #cashless comments, not many people are aware that Yakun China Square branch does offer cashless options, just because it only has one NETS terminal.
