### ISSUE TITLE
KopiJS #47 - Sunday, 11 November 2018

### ISSUE THREAD

**Issue by dexterleng** [KopiJS/kopi.js#71]
![img_20181103_130901_01](https://user-images.githubusercontent.com/34204380/48178742-4474d480-e356-11e8-880b-6bc6aaf681ce.jpg)

It's time for the November edition of Kopi.JS! Join us at Strangers' Reunion for some hipster vibes!

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Sunday, 11 November 2018, 10am**
🗺  Location: [**Strangers' Reunion**](https://foursquare.com/v/strangers-reunion/4f6d87aee4b0a6b7718a232e), [35 Kampong Bahru Rd, Singapore 169356](https://goo.gl/maps/LjQUngQKqbS2)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by aladine** [comment]
👍

**Comment by kaihendry** [comment]
https://www.youtube.com/watch?v=wOuFqvfw7zs is the video from the event!

**Comment by dexterleng** [comment]
Thanks everyone for coming! 😄

**📷 Photos**
https://twitter.com/kopi_js/status/1061519789657513984

**👨‍👩‍👧‍👦 Attendees**

- @yadunut
- @dexterleng 
- @kaihendry 
- @aladine 
- @yingkh
- @ravernkoh
- @shiling
- @PicoCreator
- @sophieyang0813
- @iynaix
- @sean1188x
- Any others?

**🗒 Notes**

- The staff did not look too happy, not exactly sure why.
- Thanks Ka Ho for making a reservation!
- We headed to the nearby prata shop afterwards.
- @kaihendry got us thinking about the first computer we got (many couldn't remember!)
