### ISSUE TITLE
KopiJS #52 - Saturday, 20 July 2019

### ISSUE THREAD

**Issue by kenzoarima** [KopiJS/kopi.js#76]
![kopijs-funan-sinpopo-1](https://user-images.githubusercontent.com/11406216/61202073-1b90b480-a719-11e9-83e7-90fbff62b348.jpg)

Funan mall, one of our go-to place for IT and electronic items, has re-opened after 3 years (😱 
 so long?) of renovation! Come drink coffee with us at this cool, Cyberpunkish, Bladerunning 🏃  place, at the Sinpopo Cafe!

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 20 July 2019, 10:57AM**
🗺  Location: **Sinpopo Coffee, Funan Mall** [#01-K02, Funan Mall, 107 North Bridge Rd, Singapore 179105](https://goo.gl/maps/x2NwgU1QtBzP4x3A7)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by kenzoarima** [comment]
inviting @PicoCreator, @shiling, @zygiss, @yangzai, @pasindud !

**Comment by kenzoarima** [comment]
Thanks everyone for coming! 😄 

### 📷 Photos

- https://twitter.com/kopi_js/status/1152432013434970113
- https://twitter.com/hj_chen/status/1152425971015753729
- https://twitter.com/kopi_js/status/1152417966291447808
- https://twitter.com/kopi_js/status/1152409790217220096
- https://twitter.com/kopi_js/status/1154614027395317760
- https://twitter.com/kopi_js/status/1154614544385245184
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- @kenzoarima 😎👕
- @cheeaun 😎👕
- @kaihendry
- @melvinzhang
- @iynaix 👕
- @miccheng 👕
- @SheldonCheng
- [pizza0502](https://twitter.com/pizza0502)
- @shiling
- @PicoCreator
- @notthetup
- @timoxley
- @weilu
- @huijing
- @serrynaimo
- [Adeline](https://www.facebook.com/adeline.setiawan)
- [Alvin](https://web.facebook.com/alvinchangw)
- @jglim
- @yadunut
- @chinying
- @wing-puah
- @hanifn
- @rubyflames
- @llun
- [Lisa Kwok](https://www.facebook.com/lisa.kwok.7)
- @yangzai
- yingkh
- Anyone else?

### 🗒 Notes

- First time drinking draft black kopi ☕️ served from the tap 🚰! As @huijing puts it, seems like she's drinking Orh Gao (aka Black Hound 🐕, aka Stout) right in the morning. On the contrast, there is overload of sugar and milk if they are part of the drink's composition.
- Many thanks to @cheeaun for the Pusheen and Popeen stickers! 😻 Ahhhh!~
- Many thanks to our pioneering attendees for coming by! 🙇 
- Some of us managed to talk to familiar faces that we saw (but never talk) at meetups.
- Only in Funan, KopiTiam is renamed as KopiTech. 🍛👾
- Special thanks to Lisa for bringing us on a tour at Wework's stylish office! 🎉
- Keep in touch and chat zany stuffs on our [Slack channel](https://launchpass.com/kopijs)! 🗣

**Comment by notthetup** [comment]
You missed @jglim

**Comment by kenzoarima** [comment]
added!

**Comment by cheeaun** [comment]
Also missed @chinying

**Comment by cheeaun** [comment]
Also @wing-puah ?

**Comment by kenzoarima** [comment]
added both! and we have 27 attendees!
