### ISSUE TITLE
KopiJS #54 - Saturday, 23 November 2019

### ISSUE THREAD

**Issue by kenzoarima** [KopiJS/kopi.js#78]
![image](https://user-images.githubusercontent.com/11406216/69246630-05719400-0be4-11ea-800e-fe5d2b5cd257.png)

⚡️ Flash Kopi.JS meetup this Saturday! An epic NERF Action Xperience playground nearby to check out too! 💥  

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 23 November 2019, 10:57AM**
🗺  Location: **dal.komm Coffee, Marina Square** [6 Raffles Blvd, Marina Square, #02-272/273 & 278, Singapore 039594](https://goo.gl/maps/StcEseF1f5mSB4oB7)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by kenzoarima** [comment]
sending invite to @pasindud, @yangzai, @melvinzhang! 💪

**Comment by ahoebeke** [comment]
Got the email notification, awesome! I usually miss notifications on other channels :)

**Comment by swyxio** [comment]
thanks for a great lunch!

**Comment by cheeaun** [comment]
Thanks everyone for coming! 😄

### 📷 Photos

- https://twitter.com/cheeaun/status/1198132418294628353
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- @cheeaun 😎
- @kenzoarima 😎
- @LoneRifle (Alwyn)
- @melvinzhang
- @Tzyinc
- @sw-yx 
- @SheldonCheng
- @iynaix
- @yingkh
- @flaki 
- @lisatjide 
- @yangzai
- Anyone else?

### 🗒 Notes

- Seems like our 3rd time at Dal.komm but in Marina Square instead. Lots of seats both inside and outside the cafe. Seat arrangements are not quite optimized for groups larger than 6 but luckily the tables and chairs are adjustable. 🪑
- It's mentioned that the coffee at Dal.komm is *cough* expensive and not*that* great ☕️ 🤔 
- Around 1PM, we shifted to EAT (beside Dal.komm) for lunch, with lots of stickers from @flaki 🍜👾 

Alright, closing the issue now...
