### ISSUE TITLE
KopiJS #55 - Saturday, 26 Aug 2023

### ISSUE THREAD

**Issue by shiling** [KopiJS/kopi.js#79]
# Rebooting kopi.js after the big achoo

![Morning Grind Cafe](https://github.com/KopiJS/kopi.js/assets/2296/4ae94233-03cf-45e2-a584-59102984bba1)

[**Kopi.JS**](https://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 26 Aug 2023, 10am - 12pm**
🗺  Location: [Morning Grind Cafe](https://morninggrindcafe.com/), [18 Cross Street #01-103 Singapore 048423](https://goo.gl/maps/XH6jVKw2UvvvQCR9A) Near Chinatown / Telok Ayer MRT

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (👍 here). Just join whenever you feel like it, no pressure ☕

**Comment by miccheng** [comment]
![image](https://github.com/KopiJS/kopi.js/assets/211980/2d5bfcdc-f506-48b0-8b7b-58b44acc417c)

# First! 🤓

**Comment by miccheng** [comment]
![image](https://github.com/KopiJS/kopi.js/assets/211980/9b247ef9-86d1-4d86-a9fd-051cfecd19ae)

![image](https://github.com/KopiJS/kopi.js/assets/211980/b9a9e7cf-14a0-49a6-9967-475d01017e7c)

Ohai! Thanks for joining us today!

**Comment by miccheng** [comment]
![image](https://github.com/KopiJS/kopi.js/assets/211980/22c45881-0521-496e-91b2-a52f9326ed6b)

## Late lunch.

**Comment by shiling** [comment]
Wow looks yummy 🤤
