### ISSUE TITLE
KopiJS #56 - Saturday, 30 Sep 2023

### ISSUE THREAD

**Issue by miccheng** [KopiJS/kopi.js#80]
# One last hurrah at Wheeler's Yard!

![Poster from Wheeler's Yard: Thank you for being part of our journey. Last day of service will be on 30th September 2023](https://github.com/KopiJS/kopi.js/assets/2296/77dc87f0-45cd-422e-b4c2-78d0669cc148)

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 30 September 2023, 1pm**
🗺  Location: [Wheeler's Yard](https://www.wheelersyard.com/), [28 Lorong Ampas, Singapore, Singapore](https://maps.app.goo.gl/tyqBtvCcqyRamq3z6)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (👍 here). Just join whenever you feel like it, no pressure ☕

**Comment by miccheng** [comment]
Updating timing to 1pm. Sorry, my previous appointment ends at 12:30pm.

**Comment by valentine** [comment]
R.I.P. [Mothershit announced it](https://www.reddit.com/r/singapore/comments/16rnfx3/bicyclethemed_cafe_wheelers_yard_closing_after_10/) too.

**Comment by paradite** [comment]
Schedule conflict for me. 😅

**Comment by miccheng** [comment]
I didn’t make any reservations. So it’s a walk-in thing. We'll try to get a table of 6 and expand later.

**Comment by miccheng** [comment]
![image](https://github.com/KopiJS/kopi.js/assets/211980/6f961583-000a-407d-82ae-8e4fc2212299)

![image](https://github.com/KopiJS/kopi.js/assets/211980/998286b7-702e-4fb0-959b-e895fa77afc6)

![image](https://github.com/KopiJS/kopi.js/assets/211980/9e888a78-bbf2-41f1-8675-ddac665b2877)

![image](https://github.com/KopiJS/kopi.js/assets/211980/231a9285-e4a9-4f64-b876-2608fa206e99)

**Comment by miccheng** [comment]
![image](https://github.com/KopiJS/kopi.js/assets/211980/811363c2-a5dc-4e28-a29d-4fe2929793c4)

![image](https://github.com/KopiJS/kopi.js/assets/211980/f12ce33a-5e51-45e3-a70a-0f6626fd7950)

![image](https://github.com/KopiJS/kopi.js/assets/211980/d0b21b4c-d314-4fbb-b112-9c7699bd3edb)

![image](https://github.com/KopiJS/kopi.js/assets/211980/e1f4333f-e3b7-41eb-88b7-71ab0e6d459a)

![image](https://github.com/KopiJS/kopi.js/assets/211980/dd9a618e-8338-4a32-b2ad-cd12c9d608d8)

![image](https://github.com/KopiJS/kopi.js/assets/211980/66ea09db-2c5c-40d8-b6e9-e185b377da1c)

![image](https://github.com/KopiJS/kopi.js/assets/211980/4a51a287-4d67-4d2b-9d35-a15c01d8168a)
