### ISSUE TITLE
 KopiJS #57 - Saturday, 2 Dec 2023

### ISSUE THREAD

**Issue by shiling** [KopiJS/kopi.js#81]
# Killing time at Killiney

![image](https://github.com/KopiJS/kopi.js/assets/2376845/6d676a8e-31c4-4b9b-8702-6fa6b863110e)

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 2 Dec 2023, 10:00am**
🗺  Location: Killiney Kopitiam - Lorong Telok @ [11 Lor Telok, Singapore 049024](https://maps.app.goo.gl/amACg2pRnhn9Z3j76)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by shiling** [comment]
Oops, I'll be arriving late at 11am +, forgotten about aircon servicing coming in... If you are early, please grab a table, turn on your nerd radar, and invite your fellow nerds to join. 🤓

**Comment by kenzoarima** [comment]
![image](https://github.com/KopiJS/kopi.js/assets/11406216/1bbb008d-9f8e-4c63-9c40-f22631a18f94) coming soon...

**Comment by chesterhow** [comment]
✌️![IMG_4174](https://github.com/KopiJS/kopi.js/assets/9312956/561041a0-9ed9-4c64-a9ba-7c8033fe4c14)
