### ISSUE TITLE
KopiJS #58 - Sunday, 28 Jan 2024

### ISSUE THREAD

**Issue by tanhauhau** [KopiJS/kopi.js#82]
Let's meet up

![173431ac-52e3-499b-9d34-94fd0c0fc7ef](https://github.com/KopiJS/kopi.js/assets/2338632/741069d9-2965-4b85-af8a-194a936d56c7)

🗓  Date: **Sunday, 28 Jan 2024, 10:00am**
🗺 Location: [Hapi Cafe](https://maps.app.goo.gl/MrRQyHLUoKjXwXDP8) 138 Cecil St, #01-02 Cecil Court, Singapore 069538

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

Q: Is this a talk with different topics or meetup?
A: Hi this one will be more chill like a meetup, I will coordinate if there are many people. it will be people grab coffee, talk and share. 

Q: I saw the cafe closes on Sunday, are you sure is it on Sunday
A: YES, I booked the time 10am - 2pm on Sunday, feel free to go, and it will open just for this event

Q: Are YK and Evan based in SG? 
A: YK is based in Vancouver but attending a Google Event in SG this week，Evan You is based in SG, that’s why it is possible to gather them and make this meet up happen

Q: Is this a regular thing? 
A: I am afraid not so far, but maybe in the future

Q: Could I join online? 
A: unfortunately not, this is an in-person event, happy to see you on Sunday.

Q: Is the event free?
A: YES, it is totally free, but you need buy your own food and drinks in HAPI cafe, I talked with the owner they are willing to give us 20% discount on selected food and drinks

**Comment by valentine** [comment]
~Google Maps says they're closed on Sundays though. Ehh…~

Edit: comment was for the old venue.

**Comment by tanhauhau** [comment]
> Google Maps says they're closed on Sundays though. Ehh…

Haiz... ok, i've updated the venue to the morning grind cafe

**Comment by chrisirhc** [comment]
> If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).

FYI neither of these links work for me. For the 2nd link I get:

> Sorry,#Kopi.JS is not currently accepting new signups

**Comment by tanhauhau** [comment]
> > If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
> 
> FYI neither of these links work for me. For the 2nd link I get:
> 
> > Sorry,#Kopi.JS is not currently accepting new signups

@chrisirhc i've updated this current issue to the [webdevsg telegram](https://t.me/WebDevSG), can find us there for this sunday.

@cheeaun kopi master, i'm not sure where we should lead people to, i just created the issue based on the template. is the kopijs slack / messenger still active?

**Comment by cheeaun** [comment]
@tanhauhau use whatever channels that's active for now.

Those two channels (Messenger + Slack) have been inactive for a long time. There's a plan to possibly migrate to a new telegram channel but I haven't look into its feasibility yet.
