### ISSUE TITLE
KopiJS #59 - Saturday, 27 Apr 2024, 10AM

### ISSUE THREAD

**Issue by shiling** [KopiJS/kopi.js#83]
# I hear the fries are good here, nice salty-esh curly fries - the best kind

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

<img width="1209" alt="image" src="https://github.com/KopiJS/kopi.js/assets/2376845/0fff021f-6731-4b15-8ffa-1f7f43afb35b">

🗓  Date: **Saturday, 27 April 2024, 10:00 AM**
🗺  Location: **Group Therapy Coffee, Cross Street Exchange**, [181 South Bridge Rd, #01-05 & #K1-04, Singapore 058743](https://maps.app.goo.gl/ApnQfGEBJXAQisYX8)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger us](https://m.me/1271249256281699), or [ping the chatroom](https://launchpass.com/kopijs).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by shiling** [comment]
On the way, might reach a little late.

**Comment by paradite** [comment]
I'm here, sitting outside.

**Comment by shiling** [comment]
See y'all next time!

![IMG_20240427_120910_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/fd6d40fd-4eb7-46cb-93f0-e271b19c8ba3)

![IMG_20240427_104921_1_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/a9c28ee0-ceac-479a-a5ca-0b9a77f31dc7)

![IMG_20240427_112537_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/003f3f8d-7c84-4a18-946e-668452597b9e)

![IMG_20240427_112551_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/a1ea630d-d314-4836-bc65-cab434409ac2)

![IMG_20240427_104835_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/c2d2a9cc-2568-4a40-b9fc-47a90372c8e0)

![IMG_20240427_104849_1_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/6f834e32-2170-4f1f-8253-a53cf52f6451)

![IMG_20240427_112555_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/56ef2ff6-fbc7-4c48-ae2c-5721da674fc7)

![IMG_20240427_104905_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/3fcf24c5-ba14-4537-843e-b11ae9557ffe)

![IMG_20240427_131531_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/aa63678c-2ba7-41d1-8521-de06ef8941a2)

![IMG_20240427_131543_HDR.jpg](https://github.com/KopiJS/kopi.js/assets/2376845/a82255b3-cf73-4603-af2f-234d73b556a1)
