### ISSUE TITLE
KopiJS #60 - Saturday, 08 Jun 2024, 10AM

### ISSUE THREAD

**Issue by shiling** [KopiJS/kopi.js#84]
# Roti Chenai, Naan desu yo!

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

![Screenshot 2024-05-31 at 7 48 35 PM](https://github.com/KopiJS/kopi.js/assets/2376845/99d9d911-6e57-4e29-a71b-aed47309ff6b)

🗓  Date: **Sat, 8 Jun 2024, 10AM**
🗺  Location: New Shah Alam Restaurant, [20-21 Circular Rd, Singapore 049376](https://maps.app.goo.gl/nqokHbw9qKamB4aj8)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by swyxio** [comment]
see u soon @tanhauhau

**Comment by shiling** [comment]
I'm here. Sitting outside. No sun today. Hope no rain. 🙏🙏

**Comment by shiling** [comment]
![IMG_20240608_105058_HDR](https://github.com/KopiJS/kopi.js/assets/2376845/34f8277f-f66f-4cff-a505-537ae088bad0)
![IMG_20240608_105120_HDR](https://github.com/KopiJS/kopi.js/assets/2376845/9349ec3f-c450-4c7d-99e0-ef3dcea24eac)
![IMG_20240608_105139_1_HDR](https://github.com/KopiJS/kopi.js/assets/2376845/e92c3ece-ef16-4701-9506-22533662d72a)
