### ISSUE TITLE
KopiJS #61 - Saturday, 19 Oct 2024, 10AM

### ISSUE THREAD

**Issue by shiling** [KopiJS/kopi.js#85]
# Take a break, have a kit kat... toast 🤨? 

![telegram-cloud-photo-size-5-6075659539081969597-y](https://github.com/user-attachments/assets/e9fe8fe5-e170-4311-81af-9bbadddd118a)

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Sat, 19 Oct 2024, 10AM**
🗺  Location: ToastBox at Breadtalk IHQ, [30 Tai Seng St, #01-05 BreadTalk IHQ, Singapore 534013](https://maps.app.goo.gl/NN88FgEDZCKMrg4ZA)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is **OPTIONAL** (👍 here). Just join whenever you feel like it, no pressure ☕

**Comment by trungvose** [comment]
Oh no, I'll be flying out to Bangok on exactly 19 Oct 😂

**Comment by ThePlasmak** [comment]
May I know how long is a typical meetup? I probably can't make it at 10 AM 😅

**Comment by shiling** [comment]
> May I know how long is a typical meetup? I probably can't make it at 10 AM 😅

People typically hang out for like 2hrs, and then it might break off into a round 2 for folks who want to have lunch nearby.

**Comment by shiling** [comment]
![IMG_20241019_094703_HDR.jpg](https://github.com/user-attachments/assets/3c4ccd15-91bc-4269-86e2-d60ad8f166c0)

Lots of seats outside. Look for a table with the Danish cookie tin.

**Comment by shiling** [comment]
We have migrated to Food Republic next door for lunch.
